# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class Bricks < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.1.8-test-ci-7"
  license "MIT"

  on_macos do
    url "https://github.mycompany.com/foo/bar/releases/download/v1.1.8-test-ci-7/bricks-cli_1.1.8-test-ci-7_darwin_all.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "1608e496527aa923a8e8c33b4adbcd5de3e400bc220194ee00e5a3860b556ab7"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.mycompany.com/foo/bar/releases/download/v1.1.8-test-ci-7/bricks-cli_1.1.8-test-ci-7_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "35be5dc047fa97b016fd4783a4468698884ae46c248ce830123fbaf61a44fb1d"

        def install
          bin.install "bricks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.mycompany.com/foo/bar/releases/download/v1.1.8-test-ci-7/bricks-cli_1.1.8-test-ci-7_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "cdd99414fbe2af4e585272ce0129e31eb62443118db653168c9b352b64854485"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      "Thank you for installing bricks! See more documentation at https://docs.bluebricks.co."
    EOS
  end
end
