# This file was generated by GoReleaser. DO NOT EDIT.
cask "bricks@1.54.2-rc.2" do
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.54.2-rc.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bricks@1.54.2-rc.2"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.54.2-rc.2/bricks_1.54.2-rc.2_darwin_all.tar.gz"
    sha256 "7659dfabf8a47a0c5038872e8175961190a8b3cc5f4849a1a36409e6a5ce27f3"
  end

  on_linux do
    on_intel do
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.54.2-rc.2/bricks_1.54.2-rc.2_linux_amd64.tar.gz"
      sha256 "bf53ee51f222a087dc5027b9ea8ad7a7c04e3f2c63e6016fe9b07419d9eb7be7"
    end
    on_arm do
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.54.2-rc.2/bricks_1.54.2-rc.2_linux_arm64.tar.gz"
      sha256 "a9579e4277a2ee2318b38ac9cb88fa3fc74b47c8b3e9a55f69dcb568b2469bdb"
    end
  end

  caveats do
    "Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co."
    "Run 'bricks --help' to get started."
  end

  # No zap stanza required
end
