# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1570Rc3 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.57.0-rc.3"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.57.0-rc.3/bricks_1.57.0-rc.3_darwin_all.tar.gz"
    sha256 "4e7a865547d0690f59b32584547dcf1357b04f26af16fcaf7afd56c913e6ef1e"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.57.0-rc.3/bricks_1.57.0-rc.3_linux_amd64.tar.gz"
      sha256 "c3ed82fb4d05aa5a16a0444b1cdd91091cb52d6695a72be65344db8647afcf90"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.57.0-rc.3/bricks_1.57.0-rc.3_linux_arm64.tar.gz"
      sha256 "f891a3377bc14b173d0e22c3a9f7b412ff4e7ab032029e693153b11ce6b61f66"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
