# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1103 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.10.3"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.10.3/bricks_1.10.3_darwin_all.tar.gz"
    sha256 "66db3b708c3d7356cba5d9dc1370abfeea9bac7caedd2f072e6a2c3dceb5046d"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.10.3/bricks_1.10.3_linux_amd64.tar.gz"
        sha256 "e195af53111d653ea824afb064abbab04b35540f8238da630430406567febdd2"

        def install
          bin.install "bricks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.10.3/bricks_1.10.3_linux_arm64.tar.gz"
        sha256 "44f2d301d5e171f8375726e528bc0f8056ab96d1e2f41a5278c037effda51d2d"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
