# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1680 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.68.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.68.0/bricks_1.68.0_darwin_all.tar.gz"
    sha256 "76ef39925f14d68a0610ef8bba6688d8e00e2d1dead305c424735249d302fe9b"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.68.0/bricks_1.68.0_linux_amd64.tar.gz"
      sha256 "7cf58f46252c0e46634a9628f098c4eb1ef0252d0af4d6ae561082376669b0b3"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.68.0/bricks_1.68.0_linux_arm64.tar.gz"
      sha256 "5a7d052e19d911075aa76645f04b2bdda46e712f44a2023b7e651481be0823b0"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
