# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1791Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.79.1-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.79.1-rc.1/bricks_1.79.1-rc.1_darwin_all.tar.gz"
    sha256 "168d42abb9ba6400ca5b04f4710ddecc26d74340d97ed77713177ae713277486"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.79.1-rc.1/bricks_1.79.1-rc.1_linux_amd64.tar.gz"
      sha256 "8c35ad9c3580e9ca7bdb1d354d19052b9323b4a888fa1eed31d25ba6ec782497"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.79.1-rc.1/bricks_1.79.1-rc.1_linux_arm64.tar.gz"
      sha256 "ce02ac37d12a80a084756d546cdd6473bb598b1915eb9a4266f9c06ce07536d4"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
