# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1321Alpha0 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.32.1-alpha.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.32.1-alpha.0/bricks_1.32.1-alpha.0_darwin_all.tar.gz"
    sha256 "acc051d319420e3b74d4d94a424ee3628ce091eab067de86cd39c59c6de94e0a"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.32.1-alpha.0/bricks_1.32.1-alpha.0_linux_amd64.tar.gz"
        sha256 "5f8b6e2f0fb7b68b271a0d14d8603db199bdc3c82d2c4d9cc69d79337cf0d4ab"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.32.1-alpha.0/bricks_1.32.1-alpha.0_linux_arm64.tar.gz"
        sha256 "768e0a5972eb44565600556e8c8c46c4839eff255f7ed19603682033c6dd4d28"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
