# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1505 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.50.5"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.50.5/bricks_1.50.5_darwin_all.tar.gz"
    sha256 "78691c65a5b4972c879d6aa5a5b53b46262fef487d06621b5c5477d5988078b9"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.50.5/bricks_1.50.5_linux_amd64.tar.gz"
      sha256 "eb759272d7528fd80a35a50b5a280ba4e1d142f6159814c12a380b9ec6ec375b"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.50.5/bricks_1.50.5_linux_arm64.tar.gz"
      sha256 "9b838d15e32a3d6fef92dce7c6efeff1e0cd90e6f69f1f24db4e6710d4ebe005"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
