# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1572McpRemote < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.57.2-mcp-remote"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.57.2-mcp-remote/bricks_1.57.2-mcp-remote_darwin_all.tar.gz"
    sha256 "0bd71313a7b4493ea87ec6a474688b03e0f10c4d082885c1e7759b0c2900eed3"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.57.2-mcp-remote/bricks_1.57.2-mcp-remote_linux_amd64.tar.gz"
      sha256 "7d813ad22de60ce0a7ae59dc7864133934f83b7a5a888f468ce39bad44e9e82d"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.57.2-mcp-remote/bricks_1.57.2-mcp-remote_linux_arm64.tar.gz"
      sha256 "e3826e2b0b8555fb83edac315da7e058450f717aa2039abeb68df4befa91bad6"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
