# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1412 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.41.2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.41.2/bricks_1.41.2_darwin_all.tar.gz"
    sha256 "3a92736e31308026e1ce4cbe3597036656816192c22993ff04fdbffb3c13216e"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.41.2/bricks_1.41.2_linux_amd64.tar.gz"
        sha256 "b16dac95bf0675c59e8434e93d2c57baf7aef08503ad3db3af2808decb2335e9"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.41.2/bricks_1.41.2_linux_arm64.tar.gz"
        sha256 "d7e3a636a9ba175287eb95fe6768c1b013e6f1b614018daf00884c9d78e971c6"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
