# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bricks < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.18.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.18.0/bricks_1.18.0_darwin_all.tar.gz"
    sha256 "35df50cfb6113f4e73b686433c7057cf3a82f123710d975224bf8bcf8730fcd0"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.18.0/bricks_1.18.0_linux_amd64.tar.gz"
        sha256 "ed5c66b55168e45a129dac0fa3cc9feda30dc50c32fbbb0867f9462548742ab2"

        def install
          bin.install "bricks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.18.0/bricks_1.18.0_linux_arm64.tar.gz"
        sha256 "8d6914e8aa99dc7a5b9ecd2eeac524490db85fa223d6b6a0d9c3a05908710378"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
