# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1340 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.34.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.34.0/bricks_1.34.0_darwin_all.tar.gz"
    sha256 "941a1026bdace177fb1f2c991c25a9a54c7075010c8b586064c63fca9a981986"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.34.0/bricks_1.34.0_linux_amd64.tar.gz"
        sha256 "6c8eafb90cef22bee42d3700da26bdd3a51eca53f17d34fa703a83a0d0c1f84c"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.34.0/bricks_1.34.0_linux_arm64.tar.gz"
        sha256 "1a1caa9aa5b4a4125fbac1c3bfab4f45c10094997f150b179fc8a4b35f573a86"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
