# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1201Rc5 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.20.1-rc5"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.20.1-rc5/bricks_1.20.1-rc5_darwin_all.tar.gz"
    sha256 "663eae06a4e4926912da3755a90726ce0dcd8d478712105ab36c8f2825f4c941"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.20.1-rc5/bricks_1.20.1-rc5_linux_amd64.tar.gz"
        sha256 "2574bc02b4367b9c8e133ef617e98c73853ff3922380fcf008aa0adfcdc2c346"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.20.1-rc5/bricks_1.20.1-rc5_linux_arm64.tar.gz"
        sha256 "0d8cc3f67a16a2e23d8d3d4890bf4eaa0dde87e30b81f4b44d72975cf4c4cae4"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
