# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1100Beta1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.10.0-beta-1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.10.0-beta-1/bricks_1.10.0-beta-1_darwin_all.tar.gz"
    sha256 "a8b6ae3bb42c5cf6f779d5c99e5139867d88adf5d880e19780aa685517f12f80"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.10.0-beta-1/bricks_1.10.0-beta-1_linux_amd64.tar.gz"
        sha256 "aafdfa7a1b62895ca2a0e4022da3d594f4095763561e1d9d5a5715bf706ae90b"

        def install
          bin.install "bricks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.10.0-beta-1/bricks_1.10.0-beta-1_linux_arm64.tar.gz"
        sha256 "28d46e4a53b05d7b244e054008985451ae8dbef77b25b2b194f8f76a090b1b60"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
