# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1451Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.45.1-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.45.1-rc/bricks_1.45.1-rc_darwin_all.tar.gz"
    sha256 "644aaf3b6840f3a4b6245a7b9ef27fd42c4bda6f29dd4fbdc92e5b2bafb268b6"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.45.1-rc/bricks_1.45.1-rc_linux_amd64.tar.gz"
      sha256 "2ac9fb760c829a42450e2ce513720ed8d4ce6676d50ab18441d4744336551554"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.45.1-rc/bricks_1.45.1-rc_linux_arm64.tar.gz"
      sha256 "223963799362df6333d8aa598c81726dee468394616b25ebb4194184087786f8"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
