# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1383Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.38.3-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.38.3-rc/bricks_1.38.3-rc_darwin_all.tar.gz"
    sha256 "b4f6805fd50b9620de50bfbbe4cec1a17f5b50e3c21f5b5a5ebc4b259bb4063f"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.38.3-rc/bricks_1.38.3-rc_linux_amd64.tar.gz"
        sha256 "8c150cbcf5adf55b3a40f37fea360136b2112cd6653a1ef5831b1a7535b79a51"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.38.3-rc/bricks_1.38.3-rc_linux_arm64.tar.gz"
        sha256 "ad96673aee06a0ad2b1cbb2f4ecb7fa913dc12e77d3a4f792f08aca67a5650c2"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
