# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1600Rc4 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.60.0-rc.4"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.60.0-rc.4/bricks_1.60.0-rc.4_darwin_all.tar.gz"
    sha256 "a10494263ef68a9d8dd54eb84bbff27df4acac0194d7e32bea08534a05f54d66"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.60.0-rc.4/bricks_1.60.0-rc.4_linux_amd64.tar.gz"
      sha256 "ddaf378cd78361bf31cc725ab5f9137eacae9ac93e8bc97b301392e5ec6029e2"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.60.0-rc.4/bricks_1.60.0-rc.4_linux_arm64.tar.gz"
      sha256 "5e6224e6c61521c674d45d280493acd78b59ad16236139e13c89384b6dee0740"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
