# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT11020 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.102.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.102.0/bricks_1.102.0_darwin_all.tar.gz"
    sha256 "c22ada014e51cf985d4f594f168b1386deb79b603fad395c6b505dd37facb5de"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.102.0/bricks_1.102.0_linux_amd64.tar.gz"
      sha256 "138c32fc9650aadf6a48f232ad55914fbd612abc0270b84d5ad9ac0955eeb876"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.102.0/bricks_1.102.0_linux_arm64.tar.gz"
      sha256 "8483000039a7812e88d50841c4863d862a781f2c7ebec62ac1b4e323c633ace3"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
