# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1506 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.50.6"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.50.6/bricks_1.50.6_darwin_all.tar.gz"
    sha256 "73d880c7fcf7d8b8650e8300639286296778e7a68a01cb36739f4e98699a0722"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.50.6/bricks_1.50.6_linux_amd64.tar.gz"
      sha256 "02579b64cc8e91a21fd5a11af5848fb6ce30b6c34ee6e94f81174582f50caff0"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.50.6/bricks_1.50.6_linux_arm64.tar.gz"
      sha256 "d620108b5b5a55ba9730dfe1de7ed6ff6844084f922d2d0faf4f71fecc1e7bbb"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
