# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1670BicepSupportRc5 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.67.0-bicep-support-rc.5"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.0-bicep-support-rc.5/bricks_1.67.0-bicep-support-rc.5_darwin_all.tar.gz"
    sha256 "7e52f40733113d2d36e767d89c6929b07e6f8fd79e04b8edd35ebb93060541cd"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.0-bicep-support-rc.5/bricks_1.67.0-bicep-support-rc.5_linux_amd64.tar.gz"
      sha256 "85e4672944323e8adf188e1e375cb2a2e4301e0b937dfa60c8488d11b121985d"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.0-bicep-support-rc.5/bricks_1.67.0-bicep-support-rc.5_linux_arm64.tar.gz"
      sha256 "e1ba87ab8dc6ef854e92be9657c6ad70b6a9678abfa828d22b3316d86db07d09"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
