# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1381Dev < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.38.1-dev"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.38.1-dev/bricks_1.38.1-dev_darwin_all.tar.gz"
    sha256 "5d6f26a5c0b09f28ef6126489bdc37857426de97896d9558819b2332483128be"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.38.1-dev/bricks_1.38.1-dev_linux_amd64.tar.gz"
        sha256 "cab2adb049842fba73183778e861828f91c5be784ade921014ef43f49baab0b9"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.38.1-dev/bricks_1.38.1-dev_linux_arm64.tar.gz"
        sha256 "1ea9f582b92bea3427cff0a302aec75bcac111ba1cb63b2b174865bb739e4243"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
