# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1830Rc3 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.83.0-rc.3"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.83.0-rc.3/bricks_1.83.0-rc.3_darwin_all.tar.gz"
    sha256 "ddadce672237cc0133a646f9dcc70b975418e85b02cf4642f278fa6e87d5a17d"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.83.0-rc.3/bricks_1.83.0-rc.3_linux_amd64.tar.gz"
      sha256 "5040909df6bf2db2aa63db7f0105d6ca3edd5fe61c3e2946a1837d48edd5c54c"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.83.0-rc.3/bricks_1.83.0-rc.3_linux_arm64.tar.gz"
      sha256 "52456cc6709ed67789d5ba70a7445fccecbae23db6877d7f06014671de7c31f0"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
