# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1821 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.82.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.82.1/bricks_1.82.1_darwin_all.tar.gz"
    sha256 "56727612c4fb4f3cc3f30d10ab78b1bd506a9b8976ae938898525a1506dc4ac4"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.82.1/bricks_1.82.1_linux_amd64.tar.gz"
      sha256 "c7ec682c72033819a3e304b30e6e093b0ee6f511adfd6a088ff1716432a978a5"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.82.1/bricks_1.82.1_linux_arm64.tar.gz"
      sha256 "ad9799ff933a6bb22a3ff099aa4cce415e59425822183d19c36b0744d62ce2ac"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
