# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1371Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.37.1-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.37.1-rc/bricks_1.37.1-rc_darwin_all.tar.gz"
    sha256 "51687db71e41ab42cdca7855d74c0991b8d577065cd805d8a76a99453fec77e7"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.37.1-rc/bricks_1.37.1-rc_linux_amd64.tar.gz"
        sha256 "462f4f032e00f0f09c57a9cc89674117024a8744ade4f67ab455652875446180"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.37.1-rc/bricks_1.37.1-rc_linux_arm64.tar.gz"
        sha256 "e2c6c003278f1cc1308b7dd043c583d24b26a9e869b5f58b25a0ff198a26a7b7"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
