# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1211Rc6 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.21.1-rc6"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.21.1-rc6/bricks_1.21.1-rc6_darwin_all.tar.gz"
    sha256 "b27c67ed141d48266a7cde08c289f9a12530a5a98091adc9984cd4817bb1995c"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.21.1-rc6/bricks_1.21.1-rc6_linux_amd64.tar.gz"
        sha256 "1dc5190ce09da1bdf8164fd7c5efcc4bd41eba198ea8b8e4cf066cf319c4e556"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.21.1-rc6/bricks_1.21.1-rc6_linux_arm64.tar.gz"
        sha256 "aa745abd1f9dade9d00392974674bee64a8115c586dca06a16466a023cde8000"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
