# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1504Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.50.4-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.50.4-rc/bricks_1.50.4-rc_darwin_all.tar.gz"
    sha256 "60dff22f47add6833419d9eecb2c80d2633607e34c7499a2afeee158a6ae59de"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.50.4-rc/bricks_1.50.4-rc_linux_amd64.tar.gz"
      sha256 "b43da3baea607a298d6402478344631bf77940ccd8a60612824be137ab6b6c91"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.50.4-rc/bricks_1.50.4-rc_linux_arm64.tar.gz"
      sha256 "7605ab4760d73292f43135b2abd1b79d48f138e0ccea3cea6be3baa0327c5df1"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
