# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1503 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.50.3"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.50.3/bricks_1.50.3_darwin_all.tar.gz"
    sha256 "35187fa11177bfb441bf6644559e383d3df617f93c28354fc7c303c5fa10f7e6"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.50.3/bricks_1.50.3_linux_amd64.tar.gz"
      sha256 "2c2b831a52bae2153b981bd15ea8a148c732f1cd302460572880bfabdba165ee"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.50.3/bricks_1.50.3_linux_arm64.tar.gz"
      sha256 "0201ca3b46ea9ffd192347e2f98823dced95c099cc6f955cc9ff1c3bdc6a7eb0"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
