# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1572McpRemotev2 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.57.2-mcp-remotev2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.57.2-mcp-remotev2/bricks_1.57.2-mcp-remotev2_darwin_all.tar.gz"
    sha256 "6bee47ba2fe236be97e89ac6124d060d4192daf622c0468ba5871792d94a2aa7"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.57.2-mcp-remotev2/bricks_1.57.2-mcp-remotev2_linux_amd64.tar.gz"
      sha256 "874e0c9a0d1c7d489a5e450279e63d6369fa87307af8c32fdd5d21767c6e9450"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.57.2-mcp-remotev2/bricks_1.57.2-mcp-remotev2_linux_arm64.tar.gz"
      sha256 "ff3fae1720b4f07a5140f8625b5eae69a151a0f3d976fce4f9c8ee6f1019e98e"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
