# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1510Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.51.0-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.51.0-rc.1/bricks_1.51.0-rc.1_darwin_all.tar.gz"
    sha256 "b3ffabd524e35ecdeffef69f047c86fedd5077954cec4aa69053783767e9991f"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.51.0-rc.1/bricks_1.51.0-rc.1_linux_amd64.tar.gz"
      sha256 "eac47460b7a8c258937c0be0cc82199a6a35c33db65a773d5329477b6e174520"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.51.0-rc.1/bricks_1.51.0-rc.1_linux_arm64.tar.gz"
      sha256 "120c9a5bc88548be1eb8a487deeaeec57990ec4e7aeb0a5fa015b21a2bfbb200"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
