# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1591Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.59.1-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.59.1-rc.1/bricks_1.59.1-rc.1_darwin_all.tar.gz"
    sha256 "16d845b8275d668b15fa82a0ad0c83bafc5afa02c8bec0d1f1db61282e3d2901"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.59.1-rc.1/bricks_1.59.1-rc.1_linux_amd64.tar.gz"
      sha256 "f4e81b1d307cf533928208d33b93c59e0284c5086f7339ed9e18128896d5671a"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.59.1-rc.1/bricks_1.59.1-rc.1_linux_arm64.tar.gz"
      sha256 "d2412704667c2b644bef59942023f6c6c5c78b52f98bb59809e0411b3b81f31f"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
