# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1490Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.49.0-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.49.0-rc/bricks_1.49.0-rc_darwin_all.tar.gz"
    sha256 "a28dfba9da3dfeaa1807daf449aeae7c470395231b6f7dcf44c10142f8713694"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.49.0-rc/bricks_1.49.0-rc_linux_amd64.tar.gz"
      sha256 "6d3d420768129c74808975a74605996744d6b95685608034532d0cfd7204a2bd"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.49.0-rc/bricks_1.49.0-rc_linux_arm64.tar.gz"
      sha256 "f9730e478e69f4f534840c5adbda3a67f233f392a5024e3f620eef84815b995c"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
