# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1542Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.54.2-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.54.2-rc.1/bricks_1.54.2-rc.1_darwin_all.tar.gz"
    sha256 "6017185188f7cdb7030ab420a795fed4a997d3a73cb55e06093bf7dd38990826"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.54.2-rc.1/bricks_1.54.2-rc.1_linux_amd64.tar.gz"
      sha256 "3a27ddefa9f3d7bfe060c8f9a5090ad6c057c740e64f8055681fcc1c438744d1"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.54.2-rc.1/bricks_1.54.2-rc.1_linux_arm64.tar.gz"
      sha256 "1b881efca1e764023cd0b578f9a72d0b84374f8ad03065b62f55e556aa7dd4fa"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
