# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1812Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.81.2-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.81.2-rc.1/bricks_1.81.2-rc.1_darwin_all.tar.gz"
    sha256 "4a7c472fab3f34765e3914c8d055a2c81e4883a5e72e35024dc03aad902b67fa"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.81.2-rc.1/bricks_1.81.2-rc.1_linux_amd64.tar.gz"
      sha256 "e3ec02519bf97f52b93bb5954cdcec4fce14c74e4a8a7baf34fb3e76f661f239"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.81.2-rc.1/bricks_1.81.2-rc.1_linux_arm64.tar.gz"
      sha256 "edb02ca85cbb20bec14c005a4b59610ef2edf5b93474075033990848b9e1a4d4"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
