# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1760Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.76.0-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.76.0-rc.1/bricks_1.76.0-rc.1_darwin_all.tar.gz"
    sha256 "2954c2635d039f5f0d431dd4b3aad69e4e67957a098bdc644775ccc80a43f237"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.76.0-rc.1/bricks_1.76.0-rc.1_linux_amd64.tar.gz"
      sha256 "56a1e74850c7652f0be11070110f5f59e68b1a0381041a7296e487d96e7658cd"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.76.0-rc.1/bricks_1.76.0-rc.1_linux_arm64.tar.gz"
      sha256 "c04a6c6b3283d59b493aa40f16dd2e8b962a1963424f6256b0ef7f5010a0275e"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
