# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1731 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.73.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.73.1/bricks_1.73.1_darwin_all.tar.gz"
    sha256 "92e6a4a89716cc43462463c6b4f3df76e780c4d509b76e518eb8e0b96438f20f"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.73.1/bricks_1.73.1_linux_amd64.tar.gz"
      sha256 "103999029f85660ddfb410ef0fcd76dd9d940a6e9006ceccd91ad43d729fb9c8"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.73.1/bricks_1.73.1_linux_arm64.tar.gz"
      sha256 "68c88c429ad98ee7589894e631754d8fc56b65720e22b47d217c51220e68b82c"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
