# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1900 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.90.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.90.0/bricks_1.90.0_darwin_all.tar.gz"
    sha256 "c0f6694665d5cbef4c43f6b8355f45dfabaf89733f62178a423aa931b96fb8ac"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.90.0/bricks_1.90.0_linux_amd64.tar.gz"
      sha256 "98da25852376e0077fae6014377322ced339e741b9d154c6e33eb376226a75d1"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.90.0/bricks_1.90.0_linux_arm64.tar.gz"
      sha256 "fe3bbd37d5779aabdf5cdc5819b4f7d0ad1e331f8004dc4f1ab5492ac2fbd5c5"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
