# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1730ArtifactlessPrjTest1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.73.0-artifactless-prj-test-1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.73.0-artifactless-prj-test-1/bricks_1.73.0-artifactless-prj-test-1_darwin_all.tar.gz"
    sha256 "cec8de86ddaec2421220674d092e3dc3f1c73ff3ec9fd99b4fbc676074afaa21"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.73.0-artifactless-prj-test-1/bricks_1.73.0-artifactless-prj-test-1_linux_amd64.tar.gz"
      sha256 "8fa0df4d451293103bdcd5a1f0b82ffb06d88d95ead02b6db1d19964a430e287"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.73.0-artifactless-prj-test-1/bricks_1.73.0-artifactless-prj-test-1_linux_arm64.tar.gz"
      sha256 "ae586fd47f9c03dd197a3f654aab689fb4895b1e27f89eeb933dea4bddab1a6c"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
