# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1681 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.68.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.68.1/bricks_1.68.1_darwin_all.tar.gz"
    sha256 "22809628b83d9068dd1aaa5073dab639b5b42807e80fc79dd0588f723237f44b"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.68.1/bricks_1.68.1_linux_amd64.tar.gz"
      sha256 "6da3b68c24a1e55b9919bebea4eab069a692a385cb452e9d728ca27f1c6c5628"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.68.1/bricks_1.68.1_linux_arm64.tar.gz"
      sha256 "748987208bc683b2d586ff8d26026065b95f940ec003390568b440c73b269ae7"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
