# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1292 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.29.2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.29.2/bricks_1.29.2_darwin_all.tar.gz"
    sha256 "c32caef05f288106591c4173f533f2ac3aef4b659c902a349663767da2c8161d"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.29.2/bricks_1.29.2_linux_amd64.tar.gz"
        sha256 "7138a849f497c9f5824a6bfbc68418b7e884e3a980222e299497eddbf7883025"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.29.2/bricks_1.29.2_linux_arm64.tar.gz"
        sha256 "427ab5324924b4f07149f577b10d782ddd76e992261b7eadaef5ff968044429e"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
