# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1330Beta < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.33.0-beta"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.33.0-beta/bricks_1.33.0-beta_darwin_all.tar.gz"
    sha256 "1812417f62accf6b4ce670f51a6b65b427a84d24988f054144473374a97d87f0"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.33.0-beta/bricks_1.33.0-beta_linux_amd64.tar.gz"
        sha256 "132bdc7111b3e9ad8138a506441468aa2b74da2c1534d8c818e9ba6bd0b4bfbd"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.33.0-beta/bricks_1.33.0-beta_linux_arm64.tar.gz"
        sha256 "396910323f503accba0f999d92800517909122296b3c3859f77a2cf16d7ed57a"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
