# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1750 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.75.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.75.0/bricks_1.75.0_darwin_all.tar.gz"
    sha256 "747ddf21f6f1a45daf8e69c927147476a6694122b2c67486e94b76f8ecf10e06"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.75.0/bricks_1.75.0_linux_amd64.tar.gz"
      sha256 "ffa2cb229d295ed67517a556f4fd50d298a73275a41423ecc0383a2c5cbc46ec"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.75.0/bricks_1.75.0_linux_arm64.tar.gz"
      sha256 "719b6b4ad4b0c94c413fe948c73bef28597b7d0f487e18529c2f1c0e14553b8b"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
