# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1781Rc0 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.78.1-rc.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.78.1-rc.0/bricks_1.78.1-rc.0_darwin_all.tar.gz"
    sha256 "df0cd4ddda09aa562b6dc84cccf44cce3ca183ba08cba72b9136d9bfa5558161"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.78.1-rc.0/bricks_1.78.1-rc.0_linux_amd64.tar.gz"
      sha256 "27fc8dc84fa8951c2fa84258e982aa93fadbb2d6050b2ced746759ff03f10301"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.78.1-rc.0/bricks_1.78.1-rc.0_linux_arm64.tar.gz"
      sha256 "d84138d49ab8919c20e6e31bd9807144350a774bb5f543f1839ae9c1fe940741"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
