# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1410Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.41.0-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.41.0-rc/bricks_1.41.0-rc_darwin_all.tar.gz"
    sha256 "127aa8a4fb9dbf9a8d1c07a5c20bb7d8d5d43140eaef5eefb32fce379519ff3e"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.41.0-rc/bricks_1.41.0-rc_linux_amd64.tar.gz"
        sha256 "01ef316ceaac63facfff63d4bc517d4fd3a5f9c791b50836656bcf835b87ba9f"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.41.0-rc/bricks_1.41.0-rc_linux_arm64.tar.gz"
        sha256 "32c46b3f5d47bcd8c606f1b95150a09f63503c80759c4c55ead30deae29869b8"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
