# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1830Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.83.0-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.83.0-rc.1/bricks_1.83.0-rc.1_darwin_all.tar.gz"
    sha256 "ef1c2327e482eb74db8ab37372c9f1d82144c2dd4b359d5a4b41a9de37b20ded"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.83.0-rc.1/bricks_1.83.0-rc.1_linux_amd64.tar.gz"
      sha256 "ab2903e79f86aa51bb7fb27d86493f173d642f0d83e5952f6f56fd477ea0e200"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.83.0-rc.1/bricks_1.83.0-rc.1_linux_arm64.tar.gz"
      sha256 "a8af92abd0e5bb0bb288c8302f68278010b7ed4686988801af849bfc53b12608"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
