# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1151TerraformTest < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.15.1-terraform-test"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.15.1-terraform-test/bricks_1.15.1-terraform-test_darwin_all.tar.gz"
    sha256 "c9f8f3da9a18f9e70eaaed5a43355cce213dca967ea2e6ef03eb33daeca1edef"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.15.1-terraform-test/bricks_1.15.1-terraform-test_linux_amd64.tar.gz"
        sha256 "faa1fda85d5952ecc645001346f5405c37d366169dc70b8d45f242bd10e0b3bb"

        def install
          bin.install "bricks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.15.1-terraform-test/bricks_1.15.1-terraform-test_linux_arm64.tar.gz"
        sha256 "71caaf4d8822f64c7879a95395d1e00eb6711af6e7de06fe9be16143aa705dee"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
