# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1242 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.24.2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.24.2/bricks_1.24.2_darwin_all.tar.gz"
    sha256 "705100173c9347a2796e28534d44fae64db23aeff6ec17de426272aa49aa7b58"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.24.2/bricks_1.24.2_linux_amd64.tar.gz"
        sha256 "3498c7f2cb1b0b1542ba7c6f8d494df942f3fdadc5ddef2f3ba92dcdf02cbe74"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.24.2/bricks_1.24.2_linux_arm64.tar.gz"
        sha256 "d7acccb6e0afc7413a4098b71dc1f36012b161b4cdf8ed140a5e2ff2831f7154"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
