# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1320Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.32.0-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.32.0-rc/bricks_1.32.0-rc_darwin_all.tar.gz"
    sha256 "2a7ad87b0be71a904c01b2aaf8e5c84fca56b964cf5365ed4e08c4c3b1cce38d"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.32.0-rc/bricks_1.32.0-rc_linux_amd64.tar.gz"
        sha256 "e92788b0b63b820dc5032af1346aa33efd80abebedb3a885c73b54fd82a918b0"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.32.0-rc/bricks_1.32.0-rc_linux_arm64.tar.gz"
        sha256 "4dec274150892f10ea8469e279bf15765c20a8826a1cb14027f50dc9f6b75500"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
