# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1440Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.44.0-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.44.0-rc/bricks_1.44.0-rc_darwin_all.tar.gz"
    sha256 "19bafd46037c9db6b409d141ac56737d06b2aff1ff90c444e53391a770b2d1f6"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.44.0-rc/bricks_1.44.0-rc_linux_amd64.tar.gz"
        sha256 "6b21bd852af92f76c0c041b6cc47526cc384fad755d7e8b7103cf5cc468edb21"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.44.0-rc/bricks_1.44.0-rc_linux_arm64.tar.gz"
        sha256 "fb801a1e740ad2c8768134d9fc22a3f189dcc8b00efdfe396a86a76fc0a3eaa4"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
