# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1550Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.55.0-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.55.0-rc.1/bricks_1.55.0-rc.1_darwin_all.tar.gz"
    sha256 "a378115695b9ea6509df351eada62d2263f674dbf80ed703928f2b387739487f"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.55.0-rc.1/bricks_1.55.0-rc.1_linux_amd64.tar.gz"
      sha256 "c07664fc3fd5ed8b3e5d18ddfcd33567d19fdfee20954446dae2291decb3567a"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.55.0-rc.1/bricks_1.55.0-rc.1_linux_arm64.tar.gz"
      sha256 "156ffae733b5a2352b1678c22451886d3d769d192a4a3aa2258957d237b713a0"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
