# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1320Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.32.0-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.32.0-rc.1/bricks_1.32.0-rc.1_darwin_all.tar.gz"
    sha256 "599e45da0e2b9d94e1c280cc722791fc94548a2b1f92888f81b10363052e0673"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.32.0-rc.1/bricks_1.32.0-rc.1_linux_amd64.tar.gz"
        sha256 "bc3d3f6e534bdac6f8039eb5625ca6eeb870cee63de30cec23487fa65693cee5"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.32.0-rc.1/bricks_1.32.0-rc.1_linux_arm64.tar.gz"
        sha256 "18b89278faf0ce875405daddcc663ef88b6cb2511f8964db20f49ef4d9b42051"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
