# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1741PlanLocationFix < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.74.1-plan-location-fix"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.74.1-plan-location-fix/bricks_1.74.1-plan-location-fix_darwin_all.tar.gz"
    sha256 "f69134fc310858c467b5cd023a0559cf5e5cf304978df5633af2052a17f17b2b"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.74.1-plan-location-fix/bricks_1.74.1-plan-location-fix_linux_amd64.tar.gz"
      sha256 "af839837caf117ebfe675ac2a53a1382891bce22d532765a11a93f910cd421c2"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.74.1-plan-location-fix/bricks_1.74.1-plan-location-fix_linux_arm64.tar.gz"
      sha256 "ef353e98ac7a526b5bf8867026b11ea59e6cfab0b009af92f2739c0055bccd63"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
