# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1231Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.23.1-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.23.1-rc/bricks_1.23.1-rc_darwin_all.tar.gz"
    sha256 "640d70b15ee3695cfbf7ee30b34662c31fa9fbe589de6172ea2b7dc142d25aea"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.23.1-rc/bricks_1.23.1-rc_linux_amd64.tar.gz"
        sha256 "0cfd8ae5d1144cc88ea9600c99b2184fff65ccefa006c582928c039504f814ed"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.23.1-rc/bricks_1.23.1-rc_linux_arm64.tar.gz"
        sha256 "7f8db733c2e9c8663f71ab91d447bf77c8a511bc4cca83273d3ec25ebe882e91"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
