# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1612Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.61.2-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.61.2-rc.1/bricks_1.61.2-rc.1_darwin_all.tar.gz"
    sha256 "b8d14b613af9fe17ed9f3b6e7f013925c15204091be394236aeb1a2d012316de"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.61.2-rc.1/bricks_1.61.2-rc.1_linux_amd64.tar.gz"
      sha256 "7ab4a763183e381de341f5c3d08b4dbf1b54bd90f276f7cd99dcd4e034523bc4"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.61.2-rc.1/bricks_1.61.2-rc.1_linux_arm64.tar.gz"
      sha256 "1ef2a6884431edc95f286155b641500eb455c7b629026539d2f40269eefc8ef3"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
