# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1211Rc2 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.21.1-rc2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.21.1-rc2/bricks_1.21.1-rc2_darwin_all.tar.gz"
    sha256 "5422562768e80425eebf863c788fbeb18e4da79faf92a8a9796a18766c77d9a8"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.21.1-rc2/bricks_1.21.1-rc2_linux_amd64.tar.gz"
        sha256 "04eedb9e218baf02016a93085136c9800d744d8393d7d58f652591165313dd1f"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.21.1-rc2/bricks_1.21.1-rc2_linux_arm64.tar.gz"
        sha256 "877f6956a0ffde777d5849ad4f644aed387910ee1802b48dec8bc551b2640577"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
