# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1340CiBeta3 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.34.0-ci-beta3"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.34.0-ci-beta3/bricks_1.34.0-ci-beta3_darwin_all.tar.gz"
    sha256 "c2ac9ffd6eb010fdad6484bfecf5b657dc28bd8046f8efd8d910c7c869154b9a"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.34.0-ci-beta3/bricks_1.34.0-ci-beta3_linux_amd64.tar.gz"
        sha256 "875dc5fd6a1e03a7a1357993014a47b8e93cf61d64de766f8b7bee6b31716154"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.34.0-ci-beta3/bricks_1.34.0-ci-beta3_linux_arm64.tar.gz"
        sha256 "1c114fb4aadb4a1f9fe049be1bfbb4fdc0e0f1514331873a50163239748d3964"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
