# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1171AwsBinPip < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.17.1-aws-bin-pip"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.17.1-aws-bin-pip/bricks_1.17.1-aws-bin-pip_darwin_all.tar.gz"
    sha256 "2b2b65fe57ba366cb6d1d62d65988fd724d7672f531b46a510381e3b8c502093"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.17.1-aws-bin-pip/bricks_1.17.1-aws-bin-pip_linux_amd64.tar.gz"
        sha256 "9d69bee2a6c10599d9741ac9296b6f37a267de3c7882081c1e4be576aba0fd09"

        def install
          bin.install "bricks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.17.1-aws-bin-pip/bricks_1.17.1-aws-bin-pip_linux_arm64.tar.gz"
        sha256 "365b046e528db681237080a42871c0ec4f14fc3c60b8dcc1415c0d245d97c4d5"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
