# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1211Rc3 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.21.1-rc3"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.21.1-rc3/bricks_1.21.1-rc3_darwin_all.tar.gz"
    sha256 "11fa589dc8065982edf1e9365b26e18bbb6af51a6176f42a34b6a303c120a4e6"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.21.1-rc3/bricks_1.21.1-rc3_linux_amd64.tar.gz"
        sha256 "b2f3587bbdfc81eb8f477743769deb45268120afeb24f26d659d79f73fa3b023"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.21.1-rc3/bricks_1.21.1-rc3_linux_arm64.tar.gz"
        sha256 "a434032674eebb54152677a765390528dcae4f9e81a288ab987d287eaffbe4b3"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
