# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1270CfMvp < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.27.0-cf-mvp"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.27.0-cf-mvp/bricks_1.27.0-cf-mvp_darwin_all.tar.gz"
    sha256 "a5b50a5661b2dd0b970baf7acc2e4d963916cb613c4163e50699b4edbeee7daa"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.27.0-cf-mvp/bricks_1.27.0-cf-mvp_linux_amd64.tar.gz"
        sha256 "b17a5a2ccdbce61ce821cd0b4ddb660295391b3db81d56290cca73d4af15a87d"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.27.0-cf-mvp/bricks_1.27.0-cf-mvp_linux_arm64.tar.gz"
        sha256 "f727f6dd00f1ffa7a637a6756ea7ed2ae604040ad14c247d04ca534b7a310167"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
