# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1610 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.61.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.61.0/bricks_1.61.0_darwin_all.tar.gz"
    sha256 "ef8071d1ac81de1cab0f1aae3d74d8b1811996a627f2478afcf047c07399cd5b"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.61.0/bricks_1.61.0_linux_amd64.tar.gz"
      sha256 "cccde128544570f778970792d496c7da50bdb22a92928b4680294719dcb0f4e1"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.61.0/bricks_1.61.0_linux_arm64.tar.gz"
      sha256 "e1cdf42fd6162872628117562d0884e7de936832857512d4ea1d303c3020804d"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
