# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1860Rc2 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.86.0-rc2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.86.0-rc2/bricks_1.86.0-rc2_darwin_all.tar.gz"
    sha256 "c051d00aa124d4288c4c75e4bdbdbc373c10fb22e995f5c4eae352bb457132e0"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.86.0-rc2/bricks_1.86.0-rc2_linux_amd64.tar.gz"
      sha256 "80510b3e4d3ddd714824740caac0944b29b5542cb626a5d7bba0819bee702db1"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.86.0-rc2/bricks_1.86.0-rc2_linux_arm64.tar.gz"
      sha256 "147081b7752c25eeff272c2f601ea489aa7bfa2f9272918e265beb0910ce0e4d"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
