# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1630 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.63.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.63.0/bricks_1.63.0_darwin_all.tar.gz"
    sha256 "0989b84c42a2f76765bd82975f135af551b056559ba7ca878894af5a4d11085a"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.63.0/bricks_1.63.0_linux_amd64.tar.gz"
      sha256 "3a48f2a776e30a85a1b01bfaca8ad744d3939301b6fad832e715aecf4f64add4"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.63.0/bricks_1.63.0_linux_arm64.tar.gz"
      sha256 "63f708319b3cd07e0298b9da50ff37e23aa8f459cb57ff735d50a9c41b77eb67"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
