# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1371 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.37.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.37.1/bricks_1.37.1_darwin_all.tar.gz"
    sha256 "c39dc06b09bfd8a1c37822538010c108b37bde7340f54381886544c7f7041d48"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.37.1/bricks_1.37.1_linux_amd64.tar.gz"
        sha256 "00332bdb8ebc9544c525a3632f45d1f42f9faa2b5b78376bd57ddd55459feba0"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.37.1/bricks_1.37.1_linux_arm64.tar.gz"
        sha256 "64be5c0e33c271bf6f29bfca870b956a084b77c6e7d572b1a829996375d87121"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
