# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1500Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.50.0-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.50.0-rc/bricks_1.50.0-rc_darwin_all.tar.gz"
    sha256 "c5045552470cfe0b2a8597db4b564a2f4c8b7a6363e65b8a7e470124e0e74544"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.50.0-rc/bricks_1.50.0-rc_linux_amd64.tar.gz"
      sha256 "7ac689dde022254dc768a13f32e4b130fcb9a408da3db691ef4b5e6c89bb4317"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.50.0-rc/bricks_1.50.0-rc_linux_arm64.tar.gz"
      sha256 "1fbaf77e126ed8ecdc267a90dfb5b899c96c81a308c0f1e25a22668a1e505879"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
