# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1770Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.77.0-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.77.0-rc.1/bricks_1.77.0-rc.1_darwin_all.tar.gz"
    sha256 "4322dc070c016a32b902d5a3a51c49a22b2e6cf2beb7e558242508555001e970"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.77.0-rc.1/bricks_1.77.0-rc.1_linux_amd64.tar.gz"
      sha256 "990ad14dce0d5055ef8d2930c69d96bfac5596443da67ea8c5a8f3ff01840924"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.77.0-rc.1/bricks_1.77.0-rc.1_linux_arm64.tar.gz"
      sha256 "2d4f696a82295ad41cda8852237cfd9225579b8eec89d0c54a97c56feaaf7f41"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
