# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1315Cc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.31.5-cc1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.31.5-cc1/bricks_1.31.5-cc1_darwin_all.tar.gz"
    sha256 "924128282c12afc04e28ed1293cbd9e3b8d9afe39932bd0c1b807671edc17ddf"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.31.5-cc1/bricks_1.31.5-cc1_linux_amd64.tar.gz"
        sha256 "4c44abf19392c506ad32ec331aa3ae7a938fe5c5390d068c28b187b8bc9901a6"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.31.5-cc1/bricks_1.31.5-cc1_linux_arm64.tar.gz"
        sha256 "df3898d9603e6e8bbd41961a3f4320bebe247c5cf6438599f7376b177c7b53f1"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
