# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1389Dev < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.38.9-dev"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.38.9-dev/bricks_1.38.9-dev_darwin_all.tar.gz"
    sha256 "e4eb5adcaf52dea321d405508bda3678039e6c704dd76ac76a72c58caf403241"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.38.9-dev/bricks_1.38.9-dev_linux_amd64.tar.gz"
        sha256 "71f308343cf8b559c681f38ce6834858463275431531bf30559a2b242733ae66"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.38.9-dev/bricks_1.38.9-dev_linux_arm64.tar.gz"
        sha256 "f5ccf6a5652bc4d1e65781d03aac6dbafcdeeecafa5b3463c5e7594e7511b346"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
