# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1810Rc2NullValueInPropFix < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.81.0-rc.2-null-value-in-prop-fix"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.81.0-rc.2-null-value-in-prop-fix/bricks_1.81.0-rc.2-null-value-in-prop-fix_darwin_all.tar.gz"
    sha256 "d29d3ca2d09f0c4eac04d2c03ba77c5911cbbd9fe361022388615b6f4096a21c"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.81.0-rc.2-null-value-in-prop-fix/bricks_1.81.0-rc.2-null-value-in-prop-fix_linux_amd64.tar.gz"
      sha256 "ae71d2150038666925648e58bdefd2a3f5edf1d4770c6cf4cdf9ee5fef0f2519"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.81.0-rc.2-null-value-in-prop-fix/bricks_1.81.0-rc.2-null-value-in-prop-fix_linux_arm64.tar.gz"
      sha256 "2d3a9fa7f03c2261f2605bad88f0632fcf02db0cd9d28a74bce41ce7c09ff567"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
