# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1461Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.46.1-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.46.1-rc/bricks_1.46.1-rc_darwin_all.tar.gz"
    sha256 "6023f760eb7e39a9a0b4dbc8ba08951f1c8ecdb8574d9fbf126bb5a65e8b99ca"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.46.1-rc/bricks_1.46.1-rc_linux_amd64.tar.gz"
      sha256 "09fc00d9e89d8a14169194fb81405c1fefbb3a3f5ed83ff3c91c5f6b7c10ae62"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.46.1-rc/bricks_1.46.1-rc_linux_arm64.tar.gz"
      sha256 "859ab4453e0f63413311365a5e465682582befb37bcedb4bee91f0e390b1ec95"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
