# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1600Rc5 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.60.0-rc.5"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.60.0-rc.5/bricks_1.60.0-rc.5_darwin_all.tar.gz"
    sha256 "746d1f01586a254381048f103ae3b76208eea47fe5777a9d3b5adec6308adbfe"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.60.0-rc.5/bricks_1.60.0-rc.5_linux_amd64.tar.gz"
      sha256 "ee64ab5a443c3259eb86dca80fac6efca35f7e2b176fe4e476518357d9d4eb10"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.60.0-rc.5/bricks_1.60.0-rc.5_linux_arm64.tar.gz"
      sha256 "02a82a38e983c889a4c38e254661ad007c5d56ce16dfc48bb3ada2f183a5495b"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
