# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1890Rc1PrFixCli791 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.89.0-rc.1-pr-fix-cli-791"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.89.0-rc.1-pr-fix-cli-791/bricks_1.89.0-rc.1-pr-fix-cli-791_darwin_all.tar.gz"
    sha256 "07690126f4a2c4f05ad56aff8acd509c5d6da0b3f15375ec6310805ed0e944d1"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.89.0-rc.1-pr-fix-cli-791/bricks_1.89.0-rc.1-pr-fix-cli-791_linux_amd64.tar.gz"
      sha256 "0b79184ae9032ea40098ec3e3b19281829580e42df722cb2caaa23b2c3bdd07c"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.89.0-rc.1-pr-fix-cli-791/bricks_1.89.0-rc.1-pr-fix-cli-791_linux_arm64.tar.gz"
      sha256 "f3a91fa8968f24043382d07fab0c15328bccfafb444332842a48a5bead674efb"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
