# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1800Rc0AgentStateUpload < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.80.0-rc.0-agent-state-upload"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.80.0-rc.0-agent-state-upload/bricks_1.80.0-rc.0-agent-state-upload_darwin_all.tar.gz"
    sha256 "70b6d40fce73e61892688753454ce5bc52bb278f5f9088c7a7a718be51362621"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.80.0-rc.0-agent-state-upload/bricks_1.80.0-rc.0-agent-state-upload_linux_amd64.tar.gz"
      sha256 "e810fb512356c6b3001a38976a0853d82a806ad0e3023459668c15ff9feccb3a"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.80.0-rc.0-agent-state-upload/bricks_1.80.0-rc.0-agent-state-upload_linux_arm64.tar.gz"
      sha256 "16c3b31c6f9c91da2e8411d61fe4a35af8541ef8d34363ea0f04bb847d5bc24d"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
