# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1290Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.29.0-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.29.0-rc/bricks_1.29.0-rc_darwin_all.tar.gz"
    sha256 "5f1c08858e7241f376e08c191af766b8d06dcfaa76119d6edc756d7e7cc417d8"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.29.0-rc/bricks_1.29.0-rc_linux_amd64.tar.gz"
        sha256 "7822266d2065b0babe66f449147ab7de3a1f9a9a195fbb3a6c906f2dab4fdcaf"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.29.0-rc/bricks_1.29.0-rc_linux_arm64.tar.gz"
        sha256 "b53dedd7b826f7a033c0d93a5ea7d059322d3d4b04f084b300a5c1acffd2a256"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
