# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1171AwsBin < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.17.1-aws-bin"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.17.1-aws-bin/bricks_1.17.1-aws-bin_darwin_all.tar.gz"
    sha256 "f8fcbe41978ac3adf97b7d9e9217dee8015a5da54aa401a4a1b48550e7a96c5f"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.17.1-aws-bin/bricks_1.17.1-aws-bin_linux_amd64.tar.gz"
        sha256 "9a5eb575211fd9f9a95cf660434de6c195300b7e7e0fb40e0b23a6bc8909a7a9"

        def install
          bin.install "bricks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.17.1-aws-bin/bricks_1.17.1-aws-bin_linux_arm64.tar.gz"
        sha256 "b82b82a35a4f17c023078e2eb9a302efc31ec233b92e9a9feee0f6ba5dfdc93e"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
