# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1151Tf185 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.15.1-tf185"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.15.1-tf185/bricks_1.15.1-tf185_darwin_all.tar.gz"
    sha256 "bf571ca51b1f7106f7134c6d94ed1f892d1ef3155dfe51fef4fd31506c3db812"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.15.1-tf185/bricks_1.15.1-tf185_linux_amd64.tar.gz"
        sha256 "c73d051db2df65746288e2ac370b87034686093db4931c96075ea6964447e095"

        def install
          bin.install "bricks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.15.1-tf185/bricks_1.15.1-tf185_linux_arm64.tar.gz"
        sha256 "1b0057a16d7dbe916eb38ce9a59936126ba833c350b7056c1f5f9fd4c96bca8b"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
