# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1550Rc2 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.55.0-rc.2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.55.0-rc.2/bricks_1.55.0-rc.2_darwin_all.tar.gz"
    sha256 "a570072f8581c0924a2d46741b306ede719401b464ba620f176d8e1e9bd1e801"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.55.0-rc.2/bricks_1.55.0-rc.2_linux_amd64.tar.gz"
      sha256 "e275e54912fc00ea22d21a1fbd3115bea3f964ccbd922ef67c6eb0c0fcfce0d8"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.55.0-rc.2/bricks_1.55.0-rc.2_linux_arm64.tar.gz"
      sha256 "cc336554d88e446c7da2a02f98d6f194691df0500cd94db25b96f9ca698a632a"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
