# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1631Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.63.1-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.63.1-rc.1/bricks_1.63.1-rc.1_darwin_all.tar.gz"
    sha256 "ebb8ae954bca5144032ef0324e4c2007d4dfc2a3c0fc626ed98740f66ae4b811"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.63.1-rc.1/bricks_1.63.1-rc.1_linux_amd64.tar.gz"
      sha256 "7bea553e2519011e481f039eb6ce5f6a7bbcfe70db16ffd7d65f2ce5778da0d9"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.63.1-rc.1/bricks_1.63.1-rc.1_linux_arm64.tar.gz"
      sha256 "9a1c074d004ae4af045e0de7a0f91725024ad3512c6875012d1ebc11a9956de1"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
