# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1630Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.63.0-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.63.0-rc/bricks_1.63.0-rc_darwin_all.tar.gz"
    sha256 "49b09f9eceabe858653b8220874c2f53fbd490f7f5b33b5e299b3af8eef7a645"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.63.0-rc/bricks_1.63.0-rc_linux_amd64.tar.gz"
      sha256 "c63c2fc8b1888532d2d9d23cfdcde50bb73622e4eae14384e4fe3bd494255fcc"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.63.0-rc/bricks_1.63.0-rc_linux_arm64.tar.gz"
      sha256 "5f3c890fdab1d670828678664937d38dfdbdb7944a136d286939f4bc01725dfe"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
