# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1381 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.38.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.38.1/bricks_1.38.1_darwin_all.tar.gz"
    sha256 "8f29b3db476370c7fedec4e6a6371d84488871daaf1a608427f611b02b9498d8"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.38.1/bricks_1.38.1_linux_amd64.tar.gz"
        sha256 "3d465ad0b8204405700041134aae1fabbac346b67066782d3a3fa2700f9434b7"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.38.1/bricks_1.38.1_linux_arm64.tar.gz"
        sha256 "c2bd3607a238ad1ce4564488925851533d4b4ea558f606b4efc80dce9d0def9e"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
