# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1671Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.67.1-rc-1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.1-rc-1/bricks_1.67.1-rc-1_darwin_all.tar.gz"
    sha256 "2e1f093010e61c7e718c417fdf0f3e0921f3484c7bcfae359250b8fa7e8490c9"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.1-rc-1/bricks_1.67.1-rc-1_linux_amd64.tar.gz"
      sha256 "64b9e4579a7828fca0e4455563e104ae8be68ba81cb19031784dc5cf982f4b32"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.1-rc-1/bricks_1.67.1-rc-1_linux_arm64.tar.gz"
      sha256 "6d2511663b37d653cf042ac42475900f6ebd3a566811f3d6479fd0d4899d43d4"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
