# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1771Rc1YamlHydration < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.77.1-rc.1-yaml-hydration"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.77.1-rc.1-yaml-hydration/bricks_1.77.1-rc.1-yaml-hydration_darwin_all.tar.gz"
    sha256 "52fdd11649f7c5daa6d324fa48e6529916d3336952c2071b6c88e7ee9b3723e7"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.77.1-rc.1-yaml-hydration/bricks_1.77.1-rc.1-yaml-hydration_linux_amd64.tar.gz"
      sha256 "c2ccddc61d7afd212a76e3c91b89ad888bb1df3ef5c7f41a9f70af246803d52b"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.77.1-rc.1-yaml-hydration/bricks_1.77.1-rc.1-yaml-hydration_linux_arm64.tar.gz"
      sha256 "d64d0c43e479601c24451edd615211474f811f0aad0ca2c8b1d05b4ac2fb9325"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
