# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1780Rc2Publisher < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.78.0-rc.2-publisher"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.78.0-rc.2-publisher/bricks_1.78.0-rc.2-publisher_darwin_all.tar.gz"
    sha256 "02e2b0a8b7d07cab291c71df521bfdc773235dd74a5d9679b844b5d2f5a0e221"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.78.0-rc.2-publisher/bricks_1.78.0-rc.2-publisher_linux_amd64.tar.gz"
      sha256 "0764f35ac6ddc5f037ed3a08e5be78dc308c3df06ee117c1968748ac8d2fb456"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.78.0-rc.2-publisher/bricks_1.78.0-rc.2-publisher_linux_arm64.tar.gz"
      sha256 "4d69502bd001fd3fad7002a603d9c6b12cb55656672613fa712080ae9e5a562c"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
