# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1401 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.40.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.40.1/bricks_1.40.1_darwin_all.tar.gz"
    sha256 "750bf9a5ced75c62c0872c41ab0f196bc3aa322ead3ff12b83ffb0a4f3f0fd1e"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.40.1/bricks_1.40.1_linux_amd64.tar.gz"
        sha256 "6978ff022af9cd2c530a6003dca211a33c40c6011f3eb9002ada2c4149eed682"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.40.1/bricks_1.40.1_linux_arm64.tar.gz"
        sha256 "edeec3f12920ff2351cf46cd2414e2f8672d6a437954807ab120f70735160702"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
