# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1740Artless2 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.74.0-artless-2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.74.0-artless-2/bricks_1.74.0-artless-2_darwin_all.tar.gz"
    sha256 "c3b23eb4754f182b693d68d710e558ab16028a61752130357db8e8d5bf9fe701"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.74.0-artless-2/bricks_1.74.0-artless-2_linux_amd64.tar.gz"
      sha256 "9e1f07815276e5bb9f95f91613af5a540eac3d3cdedfd3ac427b2cc55f031dd8"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.74.0-artless-2/bricks_1.74.0-artless-2_linux_arm64.tar.gz"
      sha256 "c84469809fc377af8682e27b50fda1469cab730c88173766ead94ff39fec16f7"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
