# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1560Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.56.0-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.56.0-rc.1/bricks_1.56.0-rc.1_darwin_all.tar.gz"
    sha256 "575dc04c6c18b404685dc80fcc57225540e74c86df06ffc8211b3d70e75cb137"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.56.0-rc.1/bricks_1.56.0-rc.1_linux_amd64.tar.gz"
      sha256 "d0ad2e06f118475fd9162184fd8a168ffce61cb92b8d94983ec67c148ee772ec"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.56.0-rc.1/bricks_1.56.0-rc.1_linux_arm64.tar.gz"
      sha256 "6c08c51a9407d151b0c0250483d08751cf5021a07eceecd9323cdc895cabe5bf"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
