# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1690 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.69.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.69.0/bricks_1.69.0_darwin_all.tar.gz"
    sha256 "5b621a36c1893a2b8f34d736f43508dfa35bd7f03dd52e7fbc932bb304c8478a"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.69.0/bricks_1.69.0_linux_amd64.tar.gz"
      sha256 "2d8428cb761ae82d6ac3adeeabf21da49f95829bb32404810b269f0dd1055e2d"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.69.0/bricks_1.69.0_linux_arm64.tar.gz"
      sha256 "ca8873e20b0e88d0e11ea1510f400a67d91cdde480e9d21274682d8945aea533"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
