# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1721Pre1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.72.1-pre.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.72.1-pre.1/bricks_1.72.1-pre.1_darwin_all.tar.gz"
    sha256 "9ee9a0dfbd12466a802f8145d13f2696566a722ba6cd00dc0fe335811fb2e05b"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.72.1-pre.1/bricks_1.72.1-pre.1_linux_amd64.tar.gz"
      sha256 "50993864dc65204ed958853371a065a2057cc324295e9623c6581865686e38cc"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.72.1-pre.1/bricks_1.72.1-pre.1_linux_arm64.tar.gz"
      sha256 "4ffeb95ef22d10daed77bafccc2b03af995b635b71f04e6d3ff72e8dbb7bc7e2"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
