# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1881Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.88.1-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.88.1-rc.1/bricks_1.88.1-rc.1_darwin_all.tar.gz"
    sha256 "5e06645ce389e08a0c2a16d16318e4478661c5a2a7d0a0cbc35231565641f1b5"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.88.1-rc.1/bricks_1.88.1-rc.1_linux_amd64.tar.gz"
      sha256 "d9c91b10fa51cb01961969d429e9446c7b44bf5b9ebd623c5bf6aea1c89f23a3"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.88.1-rc.1/bricks_1.88.1-rc.1_linux_arm64.tar.gz"
      sha256 "972445b56d9f9e7ab7932a62d327e38b2113a611c8f13f81e117740887637dfe"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
