# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1940Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.94.0-rc1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.94.0-rc1/bricks_1.94.0-rc1_darwin_all.tar.gz"
    sha256 "30dcb152e8a95b0f4556fbe6b4a5cbacc9ac8a368a689df0a7aa68caaafac2c2"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.94.0-rc1/bricks_1.94.0-rc1_linux_amd64.tar.gz"
      sha256 "ae194d844357fb4c9b005d2de2a7741781cda1b48ec206335b8644feb4d0123d"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.94.0-rc1/bricks_1.94.0-rc1_linux_arm64.tar.gz"
      sha256 "2d9b6c729097402059ad1033e0bfbc4ac5b51f57cfb3e091c037fa3aa2c88d34"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
