# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1530Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.53.0-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.53.0-rc.1/bricks_1.53.0-rc.1_darwin_all.tar.gz"
    sha256 "f6dd767f2c2797dfd2ba8deb732fbb38d15f3262ed7b80186470ea8d8d1333b0"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.53.0-rc.1/bricks_1.53.0-rc.1_linux_amd64.tar.gz"
      sha256 "98811f800ee6b0d965a85a674b1a000fcfc0c340b8e8828752c7661df361339f"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.53.0-rc.1/bricks_1.53.0-rc.1_linux_arm64.tar.gz"
      sha256 "b3864f2cf97e5e47aa477c3eefb997f0a1091df0b448cca8e5cd240adb4d481f"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
