# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1520 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.52.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.52.0/bricks_1.52.0_darwin_all.tar.gz"
    sha256 "9fa3235f9f60b99bb56e841773a4a9bfa4430f7909bbc69d38ebbaea18de01c9"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.52.0/bricks_1.52.0_linux_amd64.tar.gz"
      sha256 "46d9da59b61244eeef5d2e9205b2d38928843ee8469d37921b1b6b36d0c664b7"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.52.0/bricks_1.52.0_linux_arm64.tar.gz"
      sha256 "6e44c08cf75d090feda91a2437691268ebb8301c5791b170c93bbba3d76fa3b8"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
