# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1680Rc2BicepIncremental1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.68.0-rc.2-bicep-incremental-1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.68.0-rc.2-bicep-incremental-1/bricks_1.68.0-rc.2-bicep-incremental-1_darwin_all.tar.gz"
    sha256 "6b919c27fdf5585c07fbf6f0b0105971c2dde614d152035bcc72135968f1770e"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.68.0-rc.2-bicep-incremental-1/bricks_1.68.0-rc.2-bicep-incremental-1_linux_amd64.tar.gz"
      sha256 "e22d3b42a2185a793fd556e0b99e7b315f017fb43e07373db59d2acf989a71f3"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.68.0-rc.2-bicep-incremental-1/bricks_1.68.0-rc.2-bicep-incremental-1_linux_arm64.tar.gz"
      sha256 "64203aa5be16bfbef3e7aebf8acb451908c6b3766706fba29f6c0e09a5ce24c0"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
