# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bricks < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.5.4"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.5.4/bricks_1.5.4_darwin_all.tar.gz"
    sha256 "86bfc85310dfe02340b4edde7b129d62d65dde382a7b1fb39bdbcb7d8bc7cda8"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.5.4/bricks_1.5.4_linux_amd64.tar.gz"
        sha256 "1fcabd47e3f8e3c020857c388e3b62fd3f4d7d8ae5e7009fc7a851244740683b"

        def install
          bin.install "bricks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.5.4/bricks_1.5.4_linux_arm64.tar.gz"
        sha256 "5343559aca7c290d07461ef6cf0a2d151b3faab29e3a53d1230a577d25a15408"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
