# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1811Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.81.1-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.81.1-rc.1/bricks_1.81.1-rc.1_darwin_all.tar.gz"
    sha256 "73430b5b64330878926f1469bfe1f5161b83af1411ed9d665755b0b5508d22f9"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.81.1-rc.1/bricks_1.81.1-rc.1_linux_amd64.tar.gz"
      sha256 "5cd9b8e6fcf1c8a1ab13b29a797ab08dce0cc94508736cd8a47be089fcf8305a"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.81.1-rc.1/bricks_1.81.1-rc.1_linux_arm64.tar.gz"
      sha256 "a80950a9b05fb3ab05da25560c09b386bf5bdc31266a155d5c9c767981e3a61c"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
