# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1522Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.52.2-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.52.2-rc/bricks_1.52.2-rc_darwin_all.tar.gz"
    sha256 "796dd532eb96754163ab3bc362c2d1bbe067607458501fb9ef724889f737b85f"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.52.2-rc/bricks_1.52.2-rc_linux_amd64.tar.gz"
      sha256 "e7c96e76647397e5425747b97b1767cd384955a48238acd8fba2a0df712f9b78"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.52.2-rc/bricks_1.52.2-rc_linux_arm64.tar.gz"
      sha256 "31d1f00a53fa2297b739a01e7518a6828bd3a42df9644579b8f0a3a4f99d809c"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
