# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1783 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.78.3"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.78.3/bricks_1.78.3_darwin_all.tar.gz"
    sha256 "be87ea1eeef4d7fe7749b16cc4cfc2829eb8746b0429c5f2b90cb10d74d7bc60"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.78.3/bricks_1.78.3_linux_amd64.tar.gz"
      sha256 "7861d6cb9b437ae6487be005bf7bcc41dc70f0d728fd422a83454757718e0499"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.78.3/bricks_1.78.3_linux_arm64.tar.gz"
      sha256 "ede658def0a660d43a3ad9f2974a18d0d8499bf88e6eb44c845714e33f4eb9cb"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
