# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1340CiBeta4 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.34.0-ci-beta4"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.34.0-ci-beta4/bricks_1.34.0-ci-beta4_darwin_all.tar.gz"
    sha256 "4132f6aa2dd3b88e924418829031513ea3a17b9465b6341be4dbc3bf4a7b179b"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.34.0-ci-beta4/bricks_1.34.0-ci-beta4_linux_amd64.tar.gz"
        sha256 "1130efca5e2f30c0b567ac4270dde156a21a2bb164faa84202192a9d1d3f1b1e"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.34.0-ci-beta4/bricks_1.34.0-ci-beta4_linux_arm64.tar.gz"
        sha256 "e8e6084de35e0ea3744703867e76717ddd6a6d773b8b21d54ac1b6d62e0ffe0c"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
