# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1730Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.73.0-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.73.0-rc/bricks_1.73.0-rc_darwin_all.tar.gz"
    sha256 "789f7be86c258cef79c53e852e1009f5afa3495ed84e213ba5d81d06d2064702"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.73.0-rc/bricks_1.73.0-rc_linux_amd64.tar.gz"
      sha256 "bdf24a45419e48eaece86c6ea9af95c558d069adf711d75b327024265c4654c2"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.73.0-rc/bricks_1.73.0-rc_linux_arm64.tar.gz"
      sha256 "dba8d7a0681f91d51f36d41500413a3217795e9758b9210b990d6ec46e9fc932"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
