# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1650Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.65.0-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.65.0-rc.1/bricks_1.65.0-rc.1_darwin_all.tar.gz"
    sha256 "b45476792658ce528182594a9122e7b939cc07d70bfacbd4540bcb82fc25303a"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.65.0-rc.1/bricks_1.65.0-rc.1_linux_amd64.tar.gz"
      sha256 "0c83701123a533cf8aede2bac9d0b97ec6c629bb82e205843d181858b1d6d8f6"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.65.0-rc.1/bricks_1.65.0-rc.1_linux_arm64.tar.gz"
      sha256 "89dc9f401222e0c3df72e0b066c15107d0c3518cedc9fb851c8c21f6164b3740"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
