# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1620Rc3 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.62.0-rc.3"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.62.0-rc.3/bricks_1.62.0-rc.3_darwin_all.tar.gz"
    sha256 "afc4c84a754729a987a75fb7d56c02e197c68772f830e0d22bb0c253d186a5e2"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.62.0-rc.3/bricks_1.62.0-rc.3_linux_amd64.tar.gz"
      sha256 "a466666e4cd29d9f8d17660cccb392f6e119aecfad42b1828ee4fe9bbe9de04d"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.62.0-rc.3/bricks_1.62.0-rc.3_linux_arm64.tar.gz"
      sha256 "6540929d272af6d0a7cb8ceb405800ac0aaca5adb88c1420346d835d8cf1bc2a"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
