# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1670BicepSupportRc2 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.67.0-bicep-support-rc.2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.0-bicep-support-rc.2/bricks_1.67.0-bicep-support-rc.2_darwin_all.tar.gz"
    sha256 "b49ba7283b77ddae76cff63d221dba61da05dccdd458537663138fbe54f70f74"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.0-bicep-support-rc.2/bricks_1.67.0-bicep-support-rc.2_linux_amd64.tar.gz"
      sha256 "95f164e49b8c51d0ddd15c43831e17e97bdae63c29585a644683b1bf6be03d83"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.0-bicep-support-rc.2/bricks_1.67.0-bicep-support-rc.2_linux_arm64.tar.gz"
      sha256 "5da692081862028a10ff5d1e05a71cfabfdfe15c06d9841af5ed70749901d739"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
