# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1491 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.49.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.49.1/bricks_1.49.1_darwin_all.tar.gz"
    sha256 "0d03d5a63a45be428a17e120454487bdcf39f459937fd7f263392bf26766f005"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.49.1/bricks_1.49.1_linux_amd64.tar.gz"
      sha256 "f9668e90eb243f9ca1d1231932591575d4225f11470f88758561eedc98464dea"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.49.1/bricks_1.49.1_linux_arm64.tar.gz"
      sha256 "7fa0ec60e0743bcbfdd0f30116763777b843f60c680ec2c8c39c50ef8f9923b3"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
