# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1270CfMvp1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.27.0-cf-mvp-1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.27.0-cf-mvp-1/bricks_1.27.0-cf-mvp-1_darwin_all.tar.gz"
    sha256 "e82d3e71da1fe0012d0f1610f131282481b1e8e1ec622f40cabb6aca4cb89937"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.27.0-cf-mvp-1/bricks_1.27.0-cf-mvp-1_linux_amd64.tar.gz"
        sha256 "bccb6fb9cd0435f91cb63ee0a75501453c754ae5ccf54b68a84f9699f2136f7b"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.27.0-cf-mvp-1/bricks_1.27.0-cf-mvp-1_linux_arm64.tar.gz"
        sha256 "4ef5393b167685d406c2e050bc3b9c6a220e7014d00e6b57d69ba6e72cb608db"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
