# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1340CiBeta2 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.34.0-ci-beta2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.34.0-ci-beta2/bricks_1.34.0-ci-beta2_darwin_all.tar.gz"
    sha256 "e29581dd402610fdca5ef4210f015a3e067812c8a867ebdb7179e89423a81869"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.34.0-ci-beta2/bricks_1.34.0-ci-beta2_linux_amd64.tar.gz"
        sha256 "909f1b2349e404640c0f172b1c93dc03d31ba67dbf7f251dcc81f19fedd5d5fb"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.34.0-ci-beta2/bricks_1.34.0-ci-beta2_linux_arm64.tar.gz"
        sha256 "59d45c4f67aa8898886a912751712a2f91fd2f266fd6866469ceff79f423fb07"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
