# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1340CiBeta < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.34.0-ci-beta"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.34.0-ci-beta/bricks_1.34.0-ci-beta_darwin_all.tar.gz"
    sha256 "4a1181596d6c40ff6b22d45315ffbbf7a515f69ba7bdb480b8f418d10b134ef3"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.34.0-ci-beta/bricks_1.34.0-ci-beta_linux_amd64.tar.gz"
        sha256 "819af715494f008917a2cf46aacb187246730ad19a3d72a69b8a3c330a986739"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.34.0-ci-beta/bricks_1.34.0-ci-beta_linux_arm64.tar.gz"
        sha256 "d70520de57ec3e78885e7ad6f135603507116be8d05d3b22050ffbac59cf8d7d"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
