# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1551Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.55.1-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.55.1-rc.1/bricks_1.55.1-rc.1_darwin_all.tar.gz"
    sha256 "1b2804b8c3f9b97656d66d3238f8e3eb7bc07fd8f1cfa93f46f66d9237e6bb69"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.55.1-rc.1/bricks_1.55.1-rc.1_linux_amd64.tar.gz"
      sha256 "4c15d4a3a4b819bca2aab8534fe64c2a917f7c6f5c50f63491683857915fca79"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.55.1-rc.1/bricks_1.55.1-rc.1_linux_arm64.tar.gz"
      sha256 "83ffa525367659d3bcfd8b2d09206d976bf5b69488f71d47d13a6f540e52c50c"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
