# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1730ArtifactlessPrjTestLogs < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.73.0-artifactless-prj-test-logs"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.73.0-artifactless-prj-test-logs/bricks_1.73.0-artifactless-prj-test-logs_darwin_all.tar.gz"
    sha256 "58c3b3b9545bc8916784985bb94dd910e9d6b534c937bbb872691fd868fc0a90"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.73.0-artifactless-prj-test-logs/bricks_1.73.0-artifactless-prj-test-logs_linux_amd64.tar.gz"
      sha256 "49a89f0cb5520564e197b8c17a489975f72dc495806e99cffef71eed581aba81"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.73.0-artifactless-prj-test-logs/bricks_1.73.0-artifactless-prj-test-logs_linux_arm64.tar.gz"
      sha256 "010dd1b8008c77ee8975d027cf98924528ff8f0cf0fb4b667386c684371492aa"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
