# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1921Rc1FixImage < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.92.1-rc-1-fix-image"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.92.1-rc-1-fix-image/bricks_1.92.1-rc-1-fix-image_darwin_all.tar.gz"
    sha256 "5405a0f9b2b5472e6f50f6e887900b84a6d0fc9626cee2b4e415a0dca88a7f71"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.92.1-rc-1-fix-image/bricks_1.92.1-rc-1-fix-image_linux_amd64.tar.gz"
      sha256 "045d244e1cd7c1c3e0638eae3bbc1981b9e029ffc7345cecd91eba77a77ce278"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.92.1-rc-1-fix-image/bricks_1.92.1-rc-1-fix-image_linux_arm64.tar.gz"
      sha256 "505a70006463dab276919e9cd1d47b67ae9e851e076aa9937da2b4a5d3ed1ca1"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
