# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1851Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.85.1-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.85.1-rc/bricks_1.85.1-rc_darwin_all.tar.gz"
    sha256 "96094bfea6acdc6a38f48e3a726a82bde5b73b7571c2786c868221ace5ff22ae"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.85.1-rc/bricks_1.85.1-rc_linux_amd64.tar.gz"
      sha256 "ed69c96e83619dada1ee03f43af8ca118df328bfc5a02860f7c9bfabc12cbf98"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.85.1-rc/bricks_1.85.1-rc_linux_arm64.tar.gz"
      sha256 "eb01259b0d350ba454b5e9a22905a083ed726fd3d3d7f1f7d671dd590fe8ca01"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
