# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1831Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.83.1-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.83.1-rc.1/bricks_1.83.1-rc.1_darwin_all.tar.gz"
    sha256 "e2b765e160a40effd90c80294fa1d4fe2c469fcd9e9a537036f3ab3194dc87d8"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.83.1-rc.1/bricks_1.83.1-rc.1_linux_amd64.tar.gz"
      sha256 "b790f042644cae2821746aaafbde0774582ecfb2cf3817d50e7cd97edd8329ae"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.83.1-rc.1/bricks_1.83.1-rc.1_linux_arm64.tar.gz"
      sha256 "ba4f3a9f911f71c25a0e5a05d608d47c2bd590f5a420e315356432d7c451ac36"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
