# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1490 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.49.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.49.0/bricks_1.49.0_darwin_all.tar.gz"
    sha256 "1bfede5a889de393630ca51603228f04e470eb91b7d9159bacfbd5c3a44456d7"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.49.0/bricks_1.49.0_linux_amd64.tar.gz"
      sha256 "0bc6e763e7a07ec0d25799d4798d38ac48c8555553e8aed0415e3140faea9008"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.49.0/bricks_1.49.0_linux_arm64.tar.gz"
      sha256 "5a329264bb42b0b526c809afd19e1b92268961ca5cc21c7e61fd0528a3cb23e8"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
