# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1190 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.19.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.19.0/bricks_1.19.0_darwin_all.tar.gz"
    sha256 "096e8fc3f30490e54ebc29951c8d8f936a316c63c7751fd98c9a4f8a268d3e35"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.19.0/bricks_1.19.0_linux_amd64.tar.gz"
        sha256 "78b0820b96b396790609871c59dd01530b56549774c33105d5ff40f594bd7e81"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.19.0/bricks_1.19.0_linux_arm64.tar.gz"
        sha256 "cd28507ba5834da9f42b4342db5aa66d113012d8f118524b87196bdb2b0a7c97"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
