# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1560Rc2 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.56.0-rc.2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.56.0-rc.2/bricks_1.56.0-rc.2_darwin_all.tar.gz"
    sha256 "2caec99a37e23862ff07073519a307995d05372ef5eb00d7bd2ef91864a244c6"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.56.0-rc.2/bricks_1.56.0-rc.2_linux_amd64.tar.gz"
      sha256 "e6e13541e07d7c5d10c6da2650544e21a437ef1fbb87b92a12f0a4f214063198"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.56.0-rc.2/bricks_1.56.0-rc.2_linux_arm64.tar.gz"
      sha256 "066924417d40d5809600d97c9ba72116f88d532e682fd5cfb7d312d2a9552e45"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
