# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1740Artless1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.74.0-artless-1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.74.0-artless-1/bricks_1.74.0-artless-1_darwin_all.tar.gz"
    sha256 "f2701bbe0bfd3fe738a9c8f4e05e5a286c2094c2c244933861f8d0ceb83fa293"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.74.0-artless-1/bricks_1.74.0-artless-1_linux_amd64.tar.gz"
      sha256 "55089254fb3765d2a5b91c9a085c88f643691820f8f39a5b35204587f72a979f"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.74.0-artless-1/bricks_1.74.0-artless-1_linux_arm64.tar.gz"
      sha256 "24fccd49040a9eb75f8938bff8f5a4594b2c907237d732a969bde21cb70c3b00"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
