# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1330Beta < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.33.0-beta"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.33.0-beta/bricks_1.33.0-beta_darwin_all.tar.gz"
    sha256 "4bdbe95666130947c8007a3e60787d5e1578ed07a4af3fb3a12cc7a62980dab9"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.33.0-beta/bricks_1.33.0-beta_linux_amd64.tar.gz"
        sha256 "61f78f48f9fba29e876030b9a3b15ae9f3eba039092491521413d589f8d180fb"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.33.0-beta/bricks_1.33.0-beta_linux_arm64.tar.gz"
        sha256 "641b2b48a438d2eb7288235903aac5ee57efccd20c5e53c95ca24966c56f8d32"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
