# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1620Rc2 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.62.0-rc.2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.62.0-rc.2/bricks_1.62.0-rc.2_darwin_all.tar.gz"
    sha256 "2f614367665dcba36c963a98fdada8238fbee847f889565f732682d5e40ba042"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.62.0-rc.2/bricks_1.62.0-rc.2_linux_amd64.tar.gz"
      sha256 "b285449ac4080e8989a2f37817eabf61d4fe642f3518fc33bf648cba86e4cee5"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.62.0-rc.2/bricks_1.62.0-rc.2_linux_arm64.tar.gz"
      sha256 "7eff466242f216d099f4313a84ef6e7fb5cc1d1287e8c8684f2b7b3ac5dc74a2"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
