# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1550 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.55.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.55.0/bricks_1.55.0_darwin_all.tar.gz"
    sha256 "12c58b9d13927c909406764694853ac7f1897f7581829399a09844a97cd8522a"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.55.0/bricks_1.55.0_linux_amd64.tar.gz"
      sha256 "a1c94655e23ecb1592bc4470749eacab3a18a20350d9d885a6884d57b8b05c34"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.55.0/bricks_1.55.0_linux_arm64.tar.gz"
      sha256 "4ff8bbfdd0628cc5a134f095c000b0726d08274e67c8415de82ff2f6fc59b427"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
