# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1810Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.81.0-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.81.0-rc.1/bricks_1.81.0-rc.1_darwin_all.tar.gz"
    sha256 "c884159a281b11017f5daff8593e4981126af9bf9c182af47e6b5d7d07ac41ee"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.81.0-rc.1/bricks_1.81.0-rc.1_linux_amd64.tar.gz"
      sha256 "c952d231c6ff85875718c18a97bbb44766a18740c921fa291a76638b46efb057"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.81.0-rc.1/bricks_1.81.0-rc.1_linux_arm64.tar.gz"
      sha256 "0b621dca3dd74be2216c4d30b1b29bbd55ed17be3a3f796d9d238e0a4a2609e3"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
