# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1202 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.20.2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.20.2/bricks_1.20.2_darwin_all.tar.gz"
    sha256 "ba7047b236b05261fafe2d67623f8505f1d834908cb4f8fd5b8f2701c90c534f"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.20.2/bricks_1.20.2_linux_amd64.tar.gz"
        sha256 "158d6bbd16ee0dd63bbbac2d353c345b7cf7e36c60a891236146bcd35c7cf4c8"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.20.2/bricks_1.20.2_linux_arm64.tar.gz"
        sha256 "ffc0c43e079eddeb1e50f9a7c2260643db80ee7869dff2bb5dd9be093521e034"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
