# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1361 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.36.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.36.1/bricks_1.36.1_darwin_all.tar.gz"
    sha256 "50e048f38243f0987515e5395d1adcfd4f90f093199e1c117c01a8a764efc24c"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.36.1/bricks_1.36.1_linux_amd64.tar.gz"
        sha256 "9706f00617ae08f24a608ffd594d62dbd8baec3da2b6f97ed51b58c0ed8af711"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.36.1/bricks_1.36.1_linux_arm64.tar.gz"
        sha256 "a36dd99be08e511346ad1ec02a2c7561f12960126deac131725c2d6bacaee0e4"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
