# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1721Pre < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.72.1-pre"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.72.1-pre/bricks_1.72.1-pre_darwin_all.tar.gz"
    sha256 "20f217ed7b4f3d9f7649973f17ff2b5ccdab31a4525538e091f6f49156c59885"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.72.1-pre/bricks_1.72.1-pre_linux_amd64.tar.gz"
      sha256 "dc30ef6482a86a160eac938f6c3d4fe93984dbd6beee69468e34a1957e715ed0"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.72.1-pre/bricks_1.72.1-pre_linux_arm64.tar.gz"
      sha256 "b4038fc35ece5ef396e3ea74d8e118e66fb20e3e284c511e1c7c89f13a1b7048"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
