# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1171Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.17.1-rc1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.17.1-rc1/bricks_1.17.1-rc1_darwin_all.tar.gz"
    sha256 "486a09b3121792dfb42e8c2540b662f9ad97e035630218424d7c7358009b0481"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.17.1-rc1/bricks_1.17.1-rc1_linux_amd64.tar.gz"
        sha256 "01d145952d7afed58c9d344bbeca83c443d7ea03319e81cc2433cdcddeed4fd7"

        def install
          bin.install "bricks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.17.1-rc1/bricks_1.17.1-rc1_linux_arm64.tar.gz"
        sha256 "22b14f248e4f5a882aaee015aa627bd99a9ba6950988592545e0bd9fbe2c61b8"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
