# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1641Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.64.1-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.64.1-rc.1/bricks_1.64.1-rc.1_darwin_all.tar.gz"
    sha256 "93d381ae6babccc0835a6320c0421b143821b0930d9d629dea62caf9c56ac742"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.64.1-rc.1/bricks_1.64.1-rc.1_linux_amd64.tar.gz"
      sha256 "ab90dbd5fb9f9cec097bae22ea1d8fc99a56cc185581097ddec5307116f476fd"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.64.1-rc.1/bricks_1.64.1-rc.1_linux_arm64.tar.gz"
      sha256 "3394d2cb7bde25308945565d28073317db7c778c7515551664d54c8d6d3a6a9a"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
