# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1182 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.18.2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.18.2/bricks_1.18.2_darwin_all.tar.gz"
    sha256 "7154ee91c438f9109f96807b30469c57ea933146a46da5d9231962319e3eb831"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.18.2/bricks_1.18.2_linux_amd64.tar.gz"
        sha256 "c7161fa7251e9c1b5c099f0b2fd67aca91e4021ec34840fa1ed4659183488add"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.18.2/bricks_1.18.2_linux_arm64.tar.gz"
        sha256 "ca55f61ba6460976a0970771e2cfdbd28621e7f8db88da39064ba0cfc6fa4de4"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
