# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1510Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.51.0-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.51.0-rc/bricks_1.51.0-rc_darwin_all.tar.gz"
    sha256 "512430c155f86b2636d31eaf277ebb40b2231ccbf29b88959e0e687fdb78ba52"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.51.0-rc/bricks_1.51.0-rc_linux_amd64.tar.gz"
      sha256 "e6b4e1d2a98ba631050d9e9e6c2ccaf57fefe0ad038699972e90af8599828c6e"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.51.0-rc/bricks_1.51.0-rc_linux_arm64.tar.gz"
      sha256 "f33e73f6a66bd6d03962ad520d79ad51fbcbd3577e36235be9efb128e0f8d9c6"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
