# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1640Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.64.0-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.64.0-rc.1/bricks_1.64.0-rc.1_darwin_all.tar.gz"
    sha256 "16535e3d3977e638b4c911cca3fccf86ba15f406153331b556c27fb781b9bbdd"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.64.0-rc.1/bricks_1.64.0-rc.1_linux_amd64.tar.gz"
      sha256 "632a929181db3c646266194394e8e5daf51de0bebca5042863849f6c3bfc5c68"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.64.0-rc.1/bricks_1.64.0-rc.1_linux_arm64.tar.gz"
      sha256 "d67984105ae9b3a3da0c8efc890c4646ef0030490f62f232997318be2bd41093"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
