# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1660Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.66.0-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.66.0-rc.1/bricks_1.66.0-rc.1_darwin_all.tar.gz"
    sha256 "7d21dac31f80f76989efee642712912f8d9eb558a99ff121e2ebdf98838cf8cf"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.66.0-rc.1/bricks_1.66.0-rc.1_linux_amd64.tar.gz"
      sha256 "098f4e2753476527150cea226733cf9776698b6b6a36fe40cc8806e882df8ed7"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.66.0-rc.1/bricks_1.66.0-rc.1_linux_arm64.tar.gz"
      sha256 "5848e48334fb4c07c8a0fc9d1de15b2fd8076e8ad6a22b4ccaf5fa537938b26b"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
