# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1600Rc3 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.60.0-rc.3"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.60.0-rc.3/bricks_1.60.0-rc.3_darwin_all.tar.gz"
    sha256 "02a448810a8d969f27d029b34d962c9cbb64634377f4eebc72e5c3c11677830d"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.60.0-rc.3/bricks_1.60.0-rc.3_linux_amd64.tar.gz"
      sha256 "2347f6a061683d159d408c6e622ae168c32bc1f98849eb4d418316a9ea75ecce"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.60.0-rc.3/bricks_1.60.0-rc.3_linux_arm64.tar.gz"
      sha256 "67b929b3edce1702e4d3ef3fa75ba5f7c7f97573bff828646020ef2f8f2fc414"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
