# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1502 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.50.2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.50.2/bricks_1.50.2_darwin_all.tar.gz"
    sha256 "3e04b2a3ac331019f0abc2b54a5e1213bb2c6e681b8899eae8aacdd2abaeee3f"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.50.2/bricks_1.50.2_linux_amd64.tar.gz"
      sha256 "2c990199c30e374a59642cde4bf1ec07b2641b9f4ab08011e48c4f8186152e50"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.50.2/bricks_1.50.2_linux_arm64.tar.gz"
      sha256 "4b9ceee95a1a4eaee659d13f61ef79212f370987ffb606a59087713516401a12"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
