# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1720Winbin < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.72.0-winbin"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.72.0-winbin/bricks_1.72.0-winbin_darwin_all.tar.gz"
    sha256 "5940d7afe9968e5595e472f8430a7296c7639e2a924421c138d0c74be2aed41f"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.72.0-winbin/bricks_1.72.0-winbin_linux_amd64.tar.gz"
      sha256 "26e2166c1e2e5ef0e2d4bff67c2b7e1df576553f130714b9c5a60ac094abc1f5"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.72.0-winbin/bricks_1.72.0-winbin_linux_arm64.tar.gz"
      sha256 "e370640a2163c4c38e82bd841289bb6f10f35340e1f23c5c6efc42c2f0d6b061"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
