# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1780 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.78.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.78.0/bricks_1.78.0_darwin_all.tar.gz"
    sha256 "fdc3ef75256199e2e1884429f958ef5c90255af244979164c623eb6b27dd78f7"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.78.0/bricks_1.78.0_linux_amd64.tar.gz"
      sha256 "4d4aaf4c34f79760310cfbca4d7ee1d3fcf9f64244c0d9e59ea8fea7010039c0"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.78.0/bricks_1.78.0_linux_arm64.tar.gz"
      sha256 "d82e2502812ab0c638c0580853ae0ae8645a9fafdd2c3795e04bb980c47f4724"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
