# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1411Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.41.1-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.41.1-rc/bricks_1.41.1-rc_darwin_all.tar.gz"
    sha256 "b14e492480dc0e6a34b267c66b89325f9dd236db1214896142647c03431ea978"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.41.1-rc/bricks_1.41.1-rc_linux_amd64.tar.gz"
        sha256 "8185b0c3afeb78cc0a1cddfd4e24ff36954fb9b7cbc685e2bb1a630e35758a4a"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.41.1-rc/bricks_1.41.1-rc_linux_arm64.tar.gz"
        sha256 "b0eee42062f610236f16fa060a417dfa1e0a10cf5587f80be3d78f6da11d9e29"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
