# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1641HelmLogs < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.64.1-helm-logs"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.64.1-helm-logs/bricks_1.64.1-helm-logs_darwin_all.tar.gz"
    sha256 "5a625e56f3d05482c78933c16ed24b0951fb8264f8a8809bcb21fbaf98fc6e04"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.64.1-helm-logs/bricks_1.64.1-helm-logs_linux_amd64.tar.gz"
      sha256 "0c24b0beed7490aa0302f78d57b1f0477b42cbb30ba091301a0d3ef37278e4bc"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.64.1-helm-logs/bricks_1.64.1-helm-logs_linux_arm64.tar.gz"
      sha256 "f5cacb396c6cef2fadd50edd3f5a097b4588f9df5b1247e4114cb1e269fc1e8e"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
