# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1574 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.57.4"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.57.4/bricks_1.57.4_darwin_all.tar.gz"
    sha256 "44012c41cc041b838e307e44756e2e65a3212405bc7168e92d2ec2c828505e28"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.57.4/bricks_1.57.4_linux_amd64.tar.gz"
      sha256 "de8ffef0229762234cd5a752e91ae751caf27f9e8d28dfca6bc9bb69656d3375"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.57.4/bricks_1.57.4_linux_arm64.tar.gz"
      sha256 "7f1f911f864a107f0b5656dff2f33dd5c401f1bdff48b2f0e085214fa2fc7322"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
