# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1670BicepSupport < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.67.0-bicep-support"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.0-bicep-support/bricks_1.67.0-bicep-support_darwin_all.tar.gz"
    sha256 "c98c858c951d77ae0247a95c791bc632eeaa75aba8e8869cca8a731c7e01e220"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.0-bicep-support/bricks_1.67.0-bicep-support_linux_amd64.tar.gz"
      sha256 "6fb81527d3fe6e25007c2abb8325d7d20669f53aafd47d485073cdea98cc16d3"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.0-bicep-support/bricks_1.67.0-bicep-support_linux_arm64.tar.gz"
      sha256 "c8f6cd19f8dfe2a0fc7f3417954ae12bdf99f8b3e1c71423db25fab7e9e79318"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
