# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1832 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.83.2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.83.2/bricks_1.83.2_darwin_all.tar.gz"
    sha256 "b3e572fc2520288079ea36797a3f22bb23a4b985a718eaf8f1b6da148c53ad98"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.83.2/bricks_1.83.2_linux_amd64.tar.gz"
      sha256 "608cfeb2ef844848ebeeab392d562d222a6562802644941b395aaf54a7154d60"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.83.2/bricks_1.83.2_linux_arm64.tar.gz"
      sha256 "9457b0675c683c26c2f08e6777f5b029da827cb8837c8878e385a1e1cb6ad459"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
