# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1321Alpha1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.32.1-alpha.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.32.1-alpha.1/bricks_1.32.1-alpha.1_darwin_all.tar.gz"
    sha256 "01f20488289b021077a77f4acefea3cd90e8b6ba02c56a3ffa20e7c2e811cf42"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.32.1-alpha.1/bricks_1.32.1-alpha.1_linux_amd64.tar.gz"
        sha256 "7ecb6bcf0bb2d84ceafc2c146b17d954af8c66d0572d181310e2d1456908dbcf"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.32.1-alpha.1/bricks_1.32.1-alpha.1_linux_arm64.tar.gz"
        sha256 "7d51a100f737beb7d7e4ca9ffb4e6408620de6f6a33b600efeb8b24af22ac660"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
