# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1710RcUniqueState2 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.71.0-rc-unique-state-2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.71.0-rc-unique-state-2/bricks_1.71.0-rc-unique-state-2_darwin_all.tar.gz"
    sha256 "dd4e95344970e111cfe3bfef2a689f0a17820172e9a8e9f0cb0e3d1c0b80f7f9"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.71.0-rc-unique-state-2/bricks_1.71.0-rc-unique-state-2_linux_amd64.tar.gz"
      sha256 "72ceca1cd2e9e25e64445e1529b8977e7b70c2204da9419c7d2d1992796bea4a"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.71.0-rc-unique-state-2/bricks_1.71.0-rc-unique-state-2_linux_arm64.tar.gz"
      sha256 "d5f80aad989b4c0ea74e749792d01633b4d38d7addc91be5a118ad59376d41c9"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
