# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1650 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.65.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.65.0/bricks_1.65.0_darwin_all.tar.gz"
    sha256 "9cfe31a8d162e3a43773802814e97bef8d2df5aa53f735ea7e633d3e98f525ee"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.65.0/bricks_1.65.0_linux_amd64.tar.gz"
      sha256 "5cc2cb3b0e723e58187e51725ac6a7951e3903739b1ba213bd9019f393ee723d"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.65.0/bricks_1.65.0_linux_arm64.tar.gz"
      sha256 "1cc1d4abf9956400344d47c14c06e63a5e6fd2a485a931e15ccc315796cde3a7"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
