# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1600Rc2 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.60.0-rc.2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.60.0-rc.2/bricks_1.60.0-rc.2_darwin_all.tar.gz"
    sha256 "9423e57e064bec603871a56fe3373288f3e169aadcacc93594db1d198dedc387"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.60.0-rc.2/bricks_1.60.0-rc.2_linux_amd64.tar.gz"
      sha256 "39f99e0fff56a5e4b80911488ba22283b6abe045dad7940cce2865e8cfe22d53"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.60.0-rc.2/bricks_1.60.0-rc.2_linux_arm64.tar.gz"
      sha256 "d4941444fb0ca019d5e3348c7ac4a93ad219688bbfb6f4a98c4c6ced8d3bc011"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
