# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1502Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.50.2-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.50.2-rc/bricks_1.50.2-rc_darwin_all.tar.gz"
    sha256 "23c3d94850b021c94cd21917d27557be65f3927c87a6dd331e2575e8d6ce52d4"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.50.2-rc/bricks_1.50.2-rc_linux_amd64.tar.gz"
      sha256 "1b65d7cd084c0b02cbb81e69cf4e0a964a88c68c0447517d3b1c5e69fa78d635"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.50.2-rc/bricks_1.50.2-rc_linux_arm64.tar.gz"
      sha256 "ada9757aa29abeebc88142afdaf99309e622568b0ea101f217bce42a82e2f1c9"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
