# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1941 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.94.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.94.1/bricks_1.94.1_darwin_all.tar.gz"
    sha256 "4d57ea6feaa72583b076e1e42109f3e60ba251f2fb01826e41c76f6ded5a2c14"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.94.1/bricks_1.94.1_linux_amd64.tar.gz"
      sha256 "763ac3b12686e49b825a8588d990c84f505ff3114d7df62442a864e04a4cd051"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.94.1/bricks_1.94.1_linux_arm64.tar.gz"
      sha256 "6492e97bfa7c18c80f4a61243b3907f5dd43ce887a983fc37f22adb5dfcd123a"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
