# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1201Rc2 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.20.1-rc2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.20.1-rc2/bricks_1.20.1-rc2_darwin_all.tar.gz"
    sha256 "5ca7e833c2df89800fc3c5bd329d15ab091c9e1ae6db5530cac021da316da02d"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.20.1-rc2/bricks_1.20.1-rc2_linux_amd64.tar.gz"
        sha256 "a51ee5a5b9a9332c7f4a84e5469bc35fa9a717686f3993c5257bb4d33a43a31e"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.20.1-rc2/bricks_1.20.1-rc2_linux_arm64.tar.gz"
        sha256 "51a028f44f753b9120904e1687735057fd141744520686c2f626c0e21f1bb180"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
