# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1201Rc2 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.20.1-rc2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.20.1-rc2/bricks_1.20.1-rc2_darwin_all.tar.gz"
    sha256 "7c3239bb9487964f2e4936b454f6083420fb147d104c0d2801a9a70dc3e22dd7"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.20.1-rc2/bricks_1.20.1-rc2_linux_amd64.tar.gz"
        sha256 "211b6baec810e3f47c9f3d5fab1b8a99bf067166bad79a2151a4a968d00a2c43"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.20.1-rc2/bricks_1.20.1-rc2_linux_arm64.tar.gz"
        sha256 "25b02bb2c0fdba1b042b6d0837eafa7ad4545bdae3c3054a15fd3abda3dafdf1"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
