# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1710RcUniqueState < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.71.0-rc-unique-state"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.71.0-rc-unique-state/bricks_1.71.0-rc-unique-state_darwin_all.tar.gz"
    sha256 "63de7830132df152eff8503d045fafd7e5ce5c84c3e21b5ea9ae24d0f799750a"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.71.0-rc-unique-state/bricks_1.71.0-rc-unique-state_linux_amd64.tar.gz"
      sha256 "525078ac6f5459d3e5749780dde17c195271896cfa343349d8aaba6de782ffd3"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.71.0-rc-unique-state/bricks_1.71.0-rc-unique-state_linux_arm64.tar.gz"
      sha256 "e80502f5ff41f625517c376532ae6bc41116d4bb81ab14399b1b27bc7f0d710b"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
