# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1610Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.61.0-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.61.0-rc.1/bricks_1.61.0-rc.1_darwin_all.tar.gz"
    sha256 "f11727bd17931a76494df00362f363a417bbcbf7fe6054335b1ba8d9808490ad"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.61.0-rc.1/bricks_1.61.0-rc.1_linux_amd64.tar.gz"
      sha256 "765646854adbcbe8a8eb6d11cdffd7f5e3767922430a984dc4556207e0627b1d"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.61.0-rc.1/bricks_1.61.0-rc.1_linux_arm64.tar.gz"
      sha256 "371af4d544a7dd257bcb4230c35c9e33b466a2101f707c7a42f9d8da8b52a306"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
