# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1201Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.20.1-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.20.1-rc/bricks_1.20.1-rc_darwin_all.tar.gz"
    sha256 "b3078126419a97984571005379aed4bf309dc8f58c2e75cce3307572005a039e"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.20.1-rc/bricks_1.20.1-rc_linux_amd64.tar.gz"
        sha256 "99b3fb31913e9064181c0f5b9ea6908d4bd10be16bfbc2ddb1a94377319c54f6"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.20.1-rc/bricks_1.20.1-rc_linux_arm64.tar.gz"
        sha256 "79a1ef0f053dbf153d66db8ca8722f68ac882d3bab07675f6bb33ca56169bab4"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
