# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1211Rc5 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.21.1-rc5"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.21.1-rc5/bricks_1.21.1-rc5_darwin_all.tar.gz"
    sha256 "1dd8e736203a352c468e130894de19c98f1aa777afbf761b3907c37721b25040"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.21.1-rc5/bricks_1.21.1-rc5_linux_amd64.tar.gz"
        sha256 "920c73a42859129ccccdef096aa0fbaeece83c43d6ee3df4403b473c8bdeeefe"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.21.1-rc5/bricks_1.21.1-rc5_linux_arm64.tar.gz"
        sha256 "7f09c1117fb4bb86b2b0ce1c956f08c6f7c93042cb4c750c9a97a3bfb8480607"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
