# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1181 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.18.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.18.1/bricks_1.18.1_darwin_all.tar.gz"
    sha256 "ea80df219e0ba2feba2b86a3a42dbaaa8083d4c2383049fd7841c80b897b1a4b"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.18.1/bricks_1.18.1_linux_amd64.tar.gz"
        sha256 "81fd2b40db7114666a7da72ca9c686163926cd9d802bd7e55f5b380394ff5f8c"

        def install
          bin.install "bricks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.18.1/bricks_1.18.1_linux_arm64.tar.gz"
        sha256 "0c66ef8bd14db4c9eca9eff48ae9dc4027582058085c9480fe30b3e277dcba23"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
