# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1680Rc2BicepOuts < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.68.0-rc.2-bicep-outs"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.68.0-rc.2-bicep-outs/bricks_1.68.0-rc.2-bicep-outs_darwin_all.tar.gz"
    sha256 "dcd80f656cfb1dd1f8194f464916f9f38ded1d57da5e0bafec9d1e1a57dbdee8"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.68.0-rc.2-bicep-outs/bricks_1.68.0-rc.2-bicep-outs_linux_amd64.tar.gz"
      sha256 "dc412554f5ca620426e07785056a6e9eb968ac843059c540984b618abf4bd24c"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.68.0-rc.2-bicep-outs/bricks_1.68.0-rc.2-bicep-outs_linux_arm64.tar.gz"
      sha256 "005b1a8b5a3a5c279a8df202d59bbad08e499b7f6b0f7509ac75a04ba176238e"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
