# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT192Canary < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.9.2-canary"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.9.2-canary/bricks_1.9.2-canary_darwin_all.tar.gz"
    sha256 "3218735de36222fd39738367ebbdc4b1f29b0e4416038202a6821c413c8f1451"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.9.2-canary/bricks_1.9.2-canary_linux_amd64.tar.gz"
        sha256 "8bc52626fd3c5045970d44acd6a0056ccbaae797e3b35660348f9356e7a254fc"

        def install
          bin.install "bricks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.9.2-canary/bricks_1.9.2-canary_linux_arm64.tar.gz"
        sha256 "d9778d348421da73da35e650de7ef02da98c0cd98a0ef44a1594a707ab446564"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
