# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1420Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.42.0-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.42.0-rc/bricks_1.42.0-rc_darwin_all.tar.gz"
    sha256 "488615beb4bfe0b21df2b05f2abc69b498cee2ede919479828f6dfead9f7ef68"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.42.0-rc/bricks_1.42.0-rc_linux_amd64.tar.gz"
        sha256 "04f3850fe12f4bf2fdf586164f44eef1acb022d221187231312a138983f3938e"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.42.0-rc/bricks_1.42.0-rc_linux_arm64.tar.gz"
        sha256 "5e32e69208348fdfe232c173ea1baea49f5af0c4467bb339c94b8c1f67175afa"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
