# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1670BicepSupportRc3 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.67.0-bicep-support-rc.3"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.0-bicep-support-rc.3/bricks_1.67.0-bicep-support-rc.3_darwin_all.tar.gz"
    sha256 "b584074c31251275001e110b28a6ea59cbb02e74bfc01a82a7754d987564cad9"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.0-bicep-support-rc.3/bricks_1.67.0-bicep-support-rc.3_linux_amd64.tar.gz"
      sha256 "d8eaf23c540529c105ee1e5a8ea2d217335e527fb4af35b4af339423ca7cf4a9"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.0-bicep-support-rc.3/bricks_1.67.0-bicep-support-rc.3_linux_arm64.tar.gz"
      sha256 "640511dc38e3340ebfdb564a0e976fc209f9c45e0bb5bf0c1edac1e3acc15119"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
