# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT191Canary < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.9.1-canary"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.9.1-canary/bricks_1.9.1-canary_darwin_all.tar.gz"
    sha256 "b5ad22b8e117c2a18462bc65d631681c2521fd67ac4e3ec6605699a4ba9c6693"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.9.1-canary/bricks_1.9.1-canary_linux_amd64.tar.gz"
        sha256 "c4999521dc1dc0e4ead0b5384c07b433907efa8fb5aa4345b5172e6158b4dcf2"

        def install
          bin.install "bricks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.9.1-canary/bricks_1.9.1-canary_linux_arm64.tar.gz"
        sha256 "1a2d06c7b28e41981840281ed6fadcc1b034c673be1fbee5c9a15baac90e2b9f"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
