# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1820Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.82.0-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.82.0-rc/bricks_1.82.0-rc_darwin_all.tar.gz"
    sha256 "b52e62749a58c62422be2b0fb1b097fc611cfc4fe1a154ef923a20518582f5eb"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.82.0-rc/bricks_1.82.0-rc_linux_amd64.tar.gz"
      sha256 "c88c1722098c895691affc7ec54b591c2251641f7a9a8d388d79e188501348d0"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.82.0-rc/bricks_1.82.0-rc_linux_arm64.tar.gz"
      sha256 "43cb0598c27b49bb825bba4bfe58a7cd9c6233a75ef70485bee8ff816bdc2fdb"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
