# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1680Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.68.0-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.68.0-rc.1/bricks_1.68.0-rc.1_darwin_all.tar.gz"
    sha256 "783624722d8089631790ec89f32af891e8b0af8d8f94e016944227608c6868e2"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.68.0-rc.1/bricks_1.68.0-rc.1_linux_amd64.tar.gz"
      sha256 "4eefd669b7d16eec577bbde0c25c740efbff1d911f19a9a0677b4fd1f33ae85a"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.68.0-rc.1/bricks_1.68.0-rc.1_linux_arm64.tar.gz"
      sha256 "6fba28a3d723d940b153188d8485f905cd00068be0d0ef7c79b2c3243c8329f3"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
