# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1840Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.84.0-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.84.0-rc/bricks_1.84.0-rc_darwin_all.tar.gz"
    sha256 "bad250f43329cb8f3628fbb7aa3c599ce493c0a22a2010ecc88d5b93334a311a"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.84.0-rc/bricks_1.84.0-rc_linux_amd64.tar.gz"
      sha256 "dc2f007d7e8174ee6665719ab3c996cf3ddd82e6bde383ef4036ed77dacf749f"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.84.0-rc/bricks_1.84.0-rc_linux_arm64.tar.gz"
      sha256 "7186e684a26db32136a408a36687fbb936e23e4c0aae7ebffc8abc432d655f2b"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
