# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1411Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.41.1-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.41.1-rc/bricks_1.41.1-rc_darwin_all.tar.gz"
    sha256 "de809931f1f3e1e21da79cd8651dd9a97fba91bb2ae92357bb0bb77ca7b3cb57"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.41.1-rc/bricks_1.41.1-rc_linux_amd64.tar.gz"
        sha256 "df340c2b8b057241f2eef3768ca37a4b72720ba490353e83620ce0c6832783cd"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.41.1-rc/bricks_1.41.1-rc_linux_arm64.tar.gz"
        sha256 "5fb02e6a4fa0be059e48939653c27ff667b00f62ee328db75f6c03df1fe85cd1"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
