# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1831 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.83.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.83.1/bricks_1.83.1_darwin_all.tar.gz"
    sha256 "2eab7e6d1936714734c429b76bce5ccb59bf80fe9845d08a91776c95a243488a"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.83.1/bricks_1.83.1_linux_amd64.tar.gz"
      sha256 "363196aa5d2563509d659fc795404e1a92443ff048f032695d653f1da4287d19"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.83.1/bricks_1.83.1_linux_arm64.tar.gz"
      sha256 "2be4619042eafd808c7ed3c361c6a295df3e2d998e978485deb95dae1ca205cb"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
