# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1542Rc3 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.54.2-rc.3"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.54.2-rc.3/bricks_1.54.2-rc.3_darwin_all.tar.gz"
    sha256 "4a00615912d5ca5a618cefc523d5c82a15d3c6928339e9ff20f74d2d7e5cd248"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.54.2-rc.3/bricks_1.54.2-rc.3_linux_amd64.tar.gz"
      sha256 "273af957df0511c672562cc3cb6352cf3be58f208f88741568c4dcbefeba6e6a"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.54.2-rc.3/bricks_1.54.2-rc.3_linux_arm64.tar.gz"
      sha256 "23d6719f3d6c276f13d1c284e3f597d88f285a4096615ec2bba0969493be98a8"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
