# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1101 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.10.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.10.1/bricks_1.10.1_darwin_all.tar.gz"
    sha256 "f8410159449b0d4ff0a830758b60aa3b33c746a30920549eebe27c2e7c6fe4de"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.10.1/bricks_1.10.1_linux_amd64.tar.gz"
        sha256 "accebebe1cebdc5b53365aeb7eff07dd1a15f7fada520f518a44e7eaf5cfdc1c"

        def install
          bin.install "bricks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.10.1/bricks_1.10.1_linux_arm64.tar.gz"
        sha256 "d6df61075a8b8f3227a4e5715132427d37645e148ff98167169e5904a44fc9f6"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
