# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1490Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.49.0-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.49.0-rc.1/bricks_1.49.0-rc.1_darwin_all.tar.gz"
    sha256 "d1dd74e735cbc61ea34ac3093814dafcedcee48da033e386bf5ce9f3fe9079f2"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.49.0-rc.1/bricks_1.49.0-rc.1_linux_amd64.tar.gz"
      sha256 "c2f2430467606f70b5e09da7c55ef7d9b5e555ddc2e5c81d93b1aa8a4186e678"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.49.0-rc.1/bricks_1.49.0-rc.1_linux_arm64.tar.gz"
      sha256 "d4dc996a9ca0be5b705c7145cd05463d12696cfa2cf84f495863b772676d6651"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
