# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1460 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.46.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.46.0/bricks_1.46.0_darwin_all.tar.gz"
    sha256 "c6049ff992d553f879df793cd768cad7bd7fb6c7c96dd2ccbf32b57d49fde815"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.46.0/bricks_1.46.0_linux_amd64.tar.gz"
      sha256 "43863dd110b550c44ad9838390c2642f6ae401e8ca87fbad385ee89c09169fb1"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.46.0/bricks_1.46.0_linux_arm64.tar.gz"
      sha256 "ac737765d44ad28c4c2bc23a8b6fd08a5b5465ea9f9f2ac4913ccaee970d7120"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
