# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1591 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.59.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.59.1/bricks_1.59.1_darwin_all.tar.gz"
    sha256 "84df3def318d9d19c7ff2369b47833ba6f170fb4ab1648c80d448d17dd0b9f82"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.59.1/bricks_1.59.1_linux_amd64.tar.gz"
      sha256 "b51a93e3566d15959732cb77339e81241a74891dd919d8c004adcb77c82252a0"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.59.1/bricks_1.59.1_linux_arm64.tar.gz"
      sha256 "cdcf5eb32b1275dfa65eafc9d92aade4bec8b873b9564d0365acc4b83810de55"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
