# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1921Rc3FixImage < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.92.1-rc-3-fix-image"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.92.1-rc-3-fix-image/bricks_1.92.1-rc-3-fix-image_darwin_all.tar.gz"
    sha256 "ba1d49c8a3f2bcd332ef69dfd3cbaee05c2612e24a34cab7d997db674f9ec979"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.92.1-rc-3-fix-image/bricks_1.92.1-rc-3-fix-image_linux_amd64.tar.gz"
      sha256 "4cbb3bb4dded920fd7a90b2ff468c6967120da197c75291cbdb9ded36fefdc0a"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.92.1-rc-3-fix-image/bricks_1.92.1-rc-3-fix-image_linux_arm64.tar.gz"
      sha256 "26c1aaabc226a9d77820fcff9d853a252e32bcc623fefdcdc7847f5168358de2"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
