# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1590 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.59.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.59.0/bricks_1.59.0_darwin_all.tar.gz"
    sha256 "1bb0eda3c5b0bf157f9912ae40a9b9fca13d51218166c0f292b14c79ca718c5b"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.59.0/bricks_1.59.0_linux_amd64.tar.gz"
      sha256 "0b38a0e4fd7520f7c3dbc2aa4c6a5487a8c5238d503d3e7ecdf476a0ae153d73"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.59.0/bricks_1.59.0_linux_arm64.tar.gz"
      sha256 "5ebc37ff51735983ee0cc65df4c73eef606304e5e7659e8cce06eff4f3600b32"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
