# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1880 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.88.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.88.0/bricks_1.88.0_darwin_all.tar.gz"
    sha256 "0cfec66f83bbaf8ce4a5956a7d4f0ed0ce828b576e599228ca1044ca6a20fab1"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.88.0/bricks_1.88.0_linux_amd64.tar.gz"
      sha256 "db1ce95153eb7ff2612b6d6774eadd120c01204a10b830ca63a60df6674c4469"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.88.0/bricks_1.88.0_linux_arm64.tar.gz"
      sha256 "fa0a9d6575f897108d3dfb60d5d40622c1bab4897ef0bdc58255be338f371f81"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
