# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1771Rc2YamlHydration < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.77.1-rc.2-yaml-hydration"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.77.1-rc.2-yaml-hydration/bricks_1.77.1-rc.2-yaml-hydration_darwin_all.tar.gz"
    sha256 "a3d6f268caebae4450d5a0c2696becef989b084eff7cfcc4bb6e9fc59dc7c60f"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.77.1-rc.2-yaml-hydration/bricks_1.77.1-rc.2-yaml-hydration_linux_amd64.tar.gz"
      sha256 "f4a0405cb05e9b1d730e0e5c6b97a2310b284d1d0379addb0524a40a107d3dd5"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.77.1-rc.2-yaml-hydration/bricks_1.77.1-rc.2-yaml-hydration_linux_arm64.tar.gz"
      sha256 "ecfb3d2759ceba74cc408156ae0969f168c54b863dbf3afed7f09de689c6bdbf"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
