# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1620Rc4 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.62.0-rc.4"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.62.0-rc.4/bricks_1.62.0-rc.4_darwin_all.tar.gz"
    sha256 "c69bdb855f306b266f16b7f235cde6028ba62ce7b4fa4ddc216b1e3e3997836c"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.62.0-rc.4/bricks_1.62.0-rc.4_linux_amd64.tar.gz"
      sha256 "4169f66bd4e634146287210d975b8121399155a6e634c688b0475acbf00fe288"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.62.0-rc.4/bricks_1.62.0-rc.4_linux_arm64.tar.gz"
      sha256 "5ebbcdc6c42f7e8cfc24dfe9d483f0de52cfcfc0c15a5b363fa76b2d39edece6"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
