# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1210 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.21.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.21.0/bricks_1.21.0_darwin_all.tar.gz"
    sha256 "f3d37dbe6fe76cfc4eb589baff3394752e9f89734ca4ecd838373955f19426fc"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.21.0/bricks_1.21.0_linux_amd64.tar.gz"
        sha256 "715b830350f7c5c371278c183c78e6400ab882dc16abacdd4a08f995a50c55b5"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.21.0/bricks_1.21.0_linux_arm64.tar.gz"
        sha256 "cc0157a8695fc268b453d5aad7a553e51b43b5b8f4c68681688d5b73cfc9e51e"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
