# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1810Rc3 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.81.0-rc.3"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.81.0-rc.3/bricks_1.81.0-rc.3_darwin_all.tar.gz"
    sha256 "6190130cd6268b1bf1427e485eda342de12a6556dc6bcd443ef0af81b7794c9e"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.81.0-rc.3/bricks_1.81.0-rc.3_linux_amd64.tar.gz"
      sha256 "07f3ea701563fea9b128d218d39de08f62e73a304162303a4f8d4e9a71d0b63c"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.81.0-rc.3/bricks_1.81.0-rc.3_linux_arm64.tar.gz"
      sha256 "1fa7bc148387d2b8b28d6c4697f8cacedca1f1bf75d64ec133f60d469aaddb30"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
