# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1950 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.95.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.95.0/bricks_1.95.0_darwin_all.tar.gz"
    sha256 "5ae43f1ec543a96793cc68eeceb98c933834c42ec7aaaf18f0fd9ad8a2acc5d1"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.95.0/bricks_1.95.0_linux_amd64.tar.gz"
      sha256 "44cdfb26dd66310dfd112f3e5599a41399bcd93b79b4b44cb1223cc13abc2150"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.95.0/bricks_1.95.0_linux_arm64.tar.gz"
      sha256 "762101d79c888efaa7a89a899fbdd75760bfe8885f1008e6bc7fd74e3bcf2611"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
