# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1800 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.80.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.80.0/bricks_1.80.0_darwin_all.tar.gz"
    sha256 "7ba48c901b059e816c1262740537bf1841f6925abbe31b5a236f377b70834423"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.80.0/bricks_1.80.0_linux_amd64.tar.gz"
      sha256 "107151c7dce1caaf9a1c4ad7f9831f3498503c4acc9cf5587bb57f06bc7bf600"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.80.0/bricks_1.80.0_linux_arm64.tar.gz"
      sha256 "53f2aa67c951b26e692337e5bc11f8a8972a076f1bb2328042edd539a65ba3d3"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
