# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1711RcRootAndUniqueStates < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.71.1-rc-root-and-unique-states"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.71.1-rc-root-and-unique-states/bricks_1.71.1-rc-root-and-unique-states_darwin_all.tar.gz"
    sha256 "48e6088e06f802aea2f474e1eed1194cbd6cb8834c23a3b0923bf64e4144ec93"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.71.1-rc-root-and-unique-states/bricks_1.71.1-rc-root-and-unique-states_linux_amd64.tar.gz"
      sha256 "dd35bcf1fc32daccfead80b4cd489c70dc4e9ac5d0f1361c3ee673a93f571c2a"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.71.1-rc-root-and-unique-states/bricks_1.71.1-rc-root-and-unique-states_linux_arm64.tar.gz"
      sha256 "ca9495e15d36775c999ffa1116843bf6d226fbbd18667e06c2ce581167c92913"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
