# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1770 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.77.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.77.0/bricks_1.77.0_darwin_all.tar.gz"
    sha256 "7980d44c50aa54b5f1f08961be1edb17550ca3066a4ac404378b7669a2ebfc2d"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.77.0/bricks_1.77.0_linux_amd64.tar.gz"
      sha256 "8c9771b4d2fe48e7f811c829b04b58d094bb4804989da18dba2ce96c62dd2d9e"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.77.0/bricks_1.77.0_linux_arm64.tar.gz"
      sha256 "353ab2f03bcfb63377396b8f2bf15cb5f1e57913980004fd9860e36ab6271629"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
