# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1860Rc3 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.86.0-rc3"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.86.0-rc3/bricks_1.86.0-rc3_darwin_all.tar.gz"
    sha256 "7e525cb1a18e7426e363f1700a73b6fee04fab46f0ff285d007f61cdd9a8347c"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.86.0-rc3/bricks_1.86.0-rc3_linux_amd64.tar.gz"
      sha256 "7b7837b0d9eb35c5c8ad35d78f70751493855e7700855f12466d290e8f718670"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.86.0-rc3/bricks_1.86.0-rc3_linux_arm64.tar.gz"
      sha256 "bd054538d6f4403cb1de7ad4bbc7ff5772a71782410ae90e83e28d99665dca15"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
