# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1760 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.76.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.76.0/bricks_1.76.0_darwin_all.tar.gz"
    sha256 "fc6bc8d6fa9393c7fb8be5a83dd2afa63a7195026f0b7974f2e4106ca4b95c42"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.76.0/bricks_1.76.0_linux_amd64.tar.gz"
      sha256 "6ad13f03e6bc4ca9d7793d1e18a8b72e4cc4b3c294cf3090560936e5a2d44e35"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.76.0/bricks_1.76.0_linux_arm64.tar.gz"
      sha256 "cfa69450b50812f5963a768f7d64cea297032c779ca0a3cd09848f298d663faf"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
