# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1910 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.91.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.91.0/bricks_1.91.0_darwin_all.tar.gz"
    sha256 "73cebdc7848740563d79d66aec75a34f8aa2e261b165bada17a7d82923fcff03"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.91.0/bricks_1.91.0_linux_amd64.tar.gz"
      sha256 "a48799cde4dbec0be2b427f648164c3e02f5e62c33944ad77cb2ae242beb0115"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.91.0/bricks_1.91.0_linux_arm64.tar.gz"
      sha256 "58990730d86051c4727a672e72d98203d7c098b9504c8f2b2f46d120b902caab"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
