# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1811Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.81.1-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.81.1-rc.1/bricks_1.81.1-rc.1_darwin_all.tar.gz"
    sha256 "a70f585fa536316d212fbf2657c6d49328a8c246f8c1cd3766b027eec0454fb2"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.81.1-rc.1/bricks_1.81.1-rc.1_linux_amd64.tar.gz"
      sha256 "4533746f3033e83e01e769739227bc6a64774223025e3f792a7077b6d7f7c484"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.81.1-rc.1/bricks_1.81.1-rc.1_linux_arm64.tar.gz"
      sha256 "12f0646f2fc2c0344f792c65c04617abfaf7cacf2bf428a4df2e0ec494aba7dc"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
