# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1941Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.94.1-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.94.1-rc.1/bricks_1.94.1-rc.1_darwin_all.tar.gz"
    sha256 "eac326aee1d17959de6f489a14a21851df75256298551d681921bcf2be8a08a5"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.94.1-rc.1/bricks_1.94.1-rc.1_linux_amd64.tar.gz"
      sha256 "b7cacc704240a2032c35067a49806265c3e19e897fa1cb886979424af28094f5"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.94.1-rc.1/bricks_1.94.1-rc.1_linux_arm64.tar.gz"
      sha256 "d256d091cba472c3c2f07f3d3febaa8e60e4ea598cb94eebd87824db3271de3c"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
