# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1790Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.79.0-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.79.0-rc.1/bricks_1.79.0-rc.1_darwin_all.tar.gz"
    sha256 "742717d562fefec812107a1b3a230c8200c54b2452ff67909480a5e0817167a7"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.79.0-rc.1/bricks_1.79.0-rc.1_linux_amd64.tar.gz"
      sha256 "890c6c4895ebc635f3ffc00cff7df244d027db166da6322bc1bddc673d9c60c6"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.79.0-rc.1/bricks_1.79.0-rc.1_linux_arm64.tar.gz"
      sha256 "6eec2cd2eda3385c01bacb9abeefa3b7c98b6161a85aaa13121b924dde609930"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
