# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1670BicepSupportRc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.67.0-bicep-support-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.0-bicep-support-rc.1/bricks_1.67.0-bicep-support-rc.1_darwin_all.tar.gz"
    sha256 "f3731f02a7ea61be011682efd1c324ad85776e8d50296099f7a926527db6cf5c"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.0-bicep-support-rc.1/bricks_1.67.0-bicep-support-rc.1_linux_amd64.tar.gz"
      sha256 "505aec238680ec752412ab64385e5d172e83e4b7b53f98d06ea1f42d1639c225"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.0-bicep-support-rc.1/bricks_1.67.0-bicep-support-rc.1_linux_arm64.tar.gz"
      sha256 "fcea67cd83fa042a5805e95c481634fd4b94fdc300fae70d97aec8fcd393ef09"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
