# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1540Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.54.0-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.54.0-rc/bricks_1.54.0-rc_darwin_all.tar.gz"
    sha256 "a45dc4f9d688e0a91f7495f00ef3a27b566e292ffe460e7f8112e247842a42a2"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.54.0-rc/bricks_1.54.0-rc_linux_amd64.tar.gz"
      sha256 "6c58334426d33c36439a2400e305d64bde179cac21b907d18835a054633166e4"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.54.0-rc/bricks_1.54.0-rc_linux_arm64.tar.gz"
      sha256 "2f638e89c19b853f6838f2231fa5374da16979cc0f8d026b87d2ef697172088f"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
