# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1171AwsBinV1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.17.1-aws-bin-v1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.17.1-aws-bin-v1/bricks_1.17.1-aws-bin-v1_darwin_all.tar.gz"
    sha256 "954769027c7e522f242fa2e96e7d5108d3eda80a924fc528d46769c077f9de48"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.17.1-aws-bin-v1/bricks_1.17.1-aws-bin-v1_linux_amd64.tar.gz"
        sha256 "3bf8c04570281f935e6ab112da6508331a9dc742f1eb00883c17b4d075c545bb"

        def install
          bin.install "bricks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.17.1-aws-bin-v1/bricks_1.17.1-aws-bin-v1_linux_arm64.tar.gz"
        sha256 "9097fd5a2434fff97927fbb10ac33f5b893505af95805157c8388d79d9c3e523"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
