# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1322 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.32.2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.32.2/bricks_1.32.2_darwin_all.tar.gz"
    sha256 "d853c8a8dcbca6312fb3f3cd481ad6f9525ad74df21a4978b69e2fd9c270c450"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.32.2/bricks_1.32.2_linux_amd64.tar.gz"
        sha256 "91a39b35a9dce6b278493ab0cc021f6f7919c6a112b2686396e5d6af319c4d11"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.32.2/bricks_1.32.2_linux_arm64.tar.gz"
        sha256 "bac3240f1413e65516c713e868739296229953cd3ae27e524bb6534f2465f819"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
