# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT193Beta1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.9.3-beta-1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.9.3-beta-1/bricks_1.9.3-beta-1_darwin_all.tar.gz"
    sha256 "6bc56a03fc38dc897c8be54d152a5ecd51aa96e711acc5f6233c87101767fe67"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.9.3-beta-1/bricks_1.9.3-beta-1_linux_amd64.tar.gz"
        sha256 "d46872d15c73f9f62c24fef0958a5f3392ead6120c29a0df3615c56da34aa644"

        def install
          bin.install "bricks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.9.3-beta-1/bricks_1.9.3-beta-1_linux_arm64.tar.gz"
        sha256 "2a8304663b0f0101ed06b1fb5dee6b8fdd795473a6913adc5f4093c709ce7ae8"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
