# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1591Rc2 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.59.1-rc.2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.59.1-rc.2/bricks_1.59.1-rc.2_darwin_all.tar.gz"
    sha256 "5864f25b83335222d43e641875643f812024fb85317737f2638e9bc8d3e3fe7e"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.59.1-rc.2/bricks_1.59.1-rc.2_linux_amd64.tar.gz"
      sha256 "687d8ec8192249e53b4c28ca1d3a91cc5ec5557ee20a69bf56cfb2f69764bb13"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.59.1-rc.2/bricks_1.59.1-rc.2_linux_arm64.tar.gz"
      sha256 "bb463a9c471319f1a5d912dcb133d1412909b5b12ef70911123e91450b78ae7e"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
