# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1386 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.38.6"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.38.6/bricks_1.38.6_darwin_all.tar.gz"
    sha256 "103b95d2e6f43ccbe82a4154edf264e66101c63a56b769bf8c8b9b043681b4b4"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.38.6/bricks_1.38.6_linux_amd64.tar.gz"
        sha256 "34cb9e8086c84a8b88a264836b2151a5facfa07b6b280e1403f6d150e6df17a2"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.38.6/bricks_1.38.6_linux_arm64.tar.gz"
        sha256 "be1fa78cb0c2df2e78792453ef2550f787d2bf8a1e1b569d1e6ef3c418391ac3"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
