# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT180 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.8.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.8.0/bricks_1.8.0_darwin_all.tar.gz"
    sha256 "253df0fc0b71850fac37da44fe650cf8bff135f217722e62bc61b0ab16d28349"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.8.0/bricks_1.8.0_linux_amd64.tar.gz"
        sha256 "2cab984b08f2778945664912f0aad891b5b741ef2145ea105377df1f6718fb64"

        def install
          bin.install "bricks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.8.0/bricks_1.8.0_linux_arm64.tar.gz"
        sha256 "2f4c63635046d0a11028fb32cb92352d65ae08d1d2fa949257de4e486e283785"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
