# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1160 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.16.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.16.0/bricks_1.16.0_darwin_all.tar.gz"
    sha256 "270dd5738335107e5afb5dc55da43c9cca00e7802fc624986271b957a4c89c86"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.16.0/bricks_1.16.0_linux_amd64.tar.gz"
        sha256 "ce0391b0e76640da2e7019ab17b289bf4808b0e52eca1544879cb794cab6f14b"

        def install
          bin.install "bricks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.16.0/bricks_1.16.0_linux_arm64.tar.gz"
        sha256 "f7bbdaebbc94f11020144277a235dfad633bbfe30bb55c10378fb0b393acd90a"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
