# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1731BicepIncremental < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.73.1-bicep-incremental"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.73.1-bicep-incremental/bricks_1.73.1-bicep-incremental_darwin_all.tar.gz"
    sha256 "76934f9cbc49a3e39413e0e4020cfc5cf7dd0323576658075409587d437939b4"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.73.1-bicep-incremental/bricks_1.73.1-bicep-incremental_linux_amd64.tar.gz"
      sha256 "93e26e9fa391f5e3b3a101edac0148a4b8a0c9bafa9d9db3783ee46ded686635"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.73.1-bicep-incremental/bricks_1.73.1-bicep-incremental_linux_arm64.tar.gz"
      sha256 "1f93f36b617b17f082baca6abfffa03ca992729b046e8d4a180d04d2f6f3e8f4"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
