# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1522 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.52.2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.52.2/bricks_1.52.2_darwin_all.tar.gz"
    sha256 "0745fc7b9bddc87d29de00aa4f360c9911f74c76dced9938d0e99650213264c1"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.52.2/bricks_1.52.2_linux_amd64.tar.gz"
      sha256 "a9ce8a4b375fa9246daadb2b2713094b9d3b6f100bb2942ac6fad2a59674e031"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.52.2/bricks_1.52.2_linux_arm64.tar.gz"
      sha256 "65409f18824cdbc1d08890833905d644aa81fbc6583aa115a1d4df2ed8ec259f"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
