# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1720 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.72.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.72.0/bricks_1.72.0_darwin_all.tar.gz"
    sha256 "189009cac4846d8eb475f10658252c4a88cbc0529ae2bf3be2b61706b237a61d"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.72.0/bricks_1.72.0_linux_amd64.tar.gz"
      sha256 "37846a1db3410eb283fbdc80e11be193596116d257dd42a0e95a456cea1bf29f"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.72.0/bricks_1.72.0_linux_arm64.tar.gz"
      sha256 "38e34de85dee2f5272952933438255d4b75ba95f3da1c00d11f97bcdef4bf4d6"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
