# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1570Rc2 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.57.0-rc.2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.57.0-rc.2/bricks_1.57.0-rc.2_darwin_all.tar.gz"
    sha256 "75d6fca4c1dbd384d9cf8e708477455a1eca24f65cc8aae75f3934d6a73ba0d3"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.57.0-rc.2/bricks_1.57.0-rc.2_linux_amd64.tar.gz"
      sha256 "277fd0475e16693177761bc2dff0e82143cd9587d46d64938d46e4e652768df1"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.57.0-rc.2/bricks_1.57.0-rc.2_linux_arm64.tar.gz"
      sha256 "9a2d2a57ff93b58078f05733d18dd9e578b73eb1a1c4bcac6cc6c12e47659ffe"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
