# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1890 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.89.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.89.0/bricks_1.89.0_darwin_all.tar.gz"
    sha256 "81e6f55630f623a55f215d49992456e64bf2c65828192fffee63756a6e724466"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.89.0/bricks_1.89.0_linux_amd64.tar.gz"
      sha256 "f2c1a12921fcb3dd11d08a421e8b36ac223bff7e805bbe152c59b510320f9bba"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.89.0/bricks_1.89.0_linux_arm64.tar.gz"
      sha256 "af9264483e8d9e5a0e9b22f7735261999841c9d4515ac5782b121c2d9d59a979"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
