# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1871HfCli781 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.87.1-hf-cli-781"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.87.1-hf-cli-781/bricks_1.87.1-hf-cli-781_darwin_all.tar.gz"
    sha256 "426fa389914b14e7d0f175d440f410288bd3daeb34f2e4313c0a6997dbbc8d0b"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.87.1-hf-cli-781/bricks_1.87.1-hf-cli-781_linux_amd64.tar.gz"
      sha256 "3b46b2ee87cf224707c66473a2b5f4d24110898f9a7b05141985f0574fe97cf3"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.87.1-hf-cli-781/bricks_1.87.1-hf-cli-781_linux_arm64.tar.gz"
      sha256 "9b7f3ffc22876ddb8bd193a64494cb06b2c255b6af714adce07cbfa63ab6d812"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
