# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1700 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.70.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.70.0/bricks_1.70.0_darwin_all.tar.gz"
    sha256 "62102c86d781dc57b30a7a11f7a39c0d861484a54443bd3eb863aeeeda90d368"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.70.0/bricks_1.70.0_linux_amd64.tar.gz"
      sha256 "91e75a9ea55ffdc75f1f4021dee48c3c473a970782cdcdc372c4535beb311f5c"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.70.0/bricks_1.70.0_linux_arm64.tar.gz"
      sha256 "05b983a67cb331d513e2fc2084c2fc061e3a3296885c3779933173ddfaf518e5"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
