# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1350Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.35.0-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.35.0-rc/bricks_1.35.0-rc_darwin_all.tar.gz"
    sha256 "2c60ffa981f7260b9a11341b3f1d6ec1edb7dc2d7f6d608e1a290feb2576aa3e"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.35.0-rc/bricks_1.35.0-rc_linux_amd64.tar.gz"
        sha256 "a24f9306e8bfbb32f29ff38832b18092b8c5c8c4eddd3a394923d0a22c6bde71"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.35.0-rc/bricks_1.35.0-rc_linux_arm64.tar.gz"
        sha256 "995f705aff039ee10e50be038d196c003301a7bab8040c94dea59dd28fd8dd35"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
