# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1390Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.39.0-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.39.0-rc/bricks_1.39.0-rc_darwin_all.tar.gz"
    sha256 "8894cae478a51019551b053a05781365baba4967ee68b0324648180594cdb567"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.39.0-rc/bricks_1.39.0-rc_linux_amd64.tar.gz"
        sha256 "d2d31b204db2297a1f5f9c4debc7c217b8bb1a2bde711abeae9fa5536c8ddfcd"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.39.0-rc/bricks_1.39.0-rc_linux_arm64.tar.gz"
        sha256 "f422834175edc28c75fb4c3f158a6ddca990767f884bcbdd092be10740b14027"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
