# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1670BicepSupportRc4 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.67.0-bicep-support-rc.4"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.0-bicep-support-rc.4/bricks_1.67.0-bicep-support-rc.4_darwin_all.tar.gz"
    sha256 "e368dc35011ae973130baf4aa6d0fe63b713c4c34d36ba9ea559b63441f74c79"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.0-bicep-support-rc.4/bricks_1.67.0-bicep-support-rc.4_linux_amd64.tar.gz"
      sha256 "db08c45469b336dcb96c5a22637b334dc3a3fd0b2efc253357eb11e5fd079ca1"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.0-bicep-support-rc.4/bricks_1.67.0-bicep-support-rc.4_linux_arm64.tar.gz"
      sha256 "91d6a6ffeb46ca1d641dc9d58d1cbd0e919f3face97269dd38f025a7d13e707e"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
