# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1291Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.29.1-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.29.1-rc/bricks_1.29.1-rc_darwin_all.tar.gz"
    sha256 "71f65ee4c01330397b7a6f083048ca7b75dd8e1cb89bd6cfab2a83aba7d50243"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.29.1-rc/bricks_1.29.1-rc_linux_amd64.tar.gz"
        sha256 "3f86f2ad3c0f3d4b34680829c0e90b8dcfc88b6795f4db4928dc2088f65f0228"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.29.1-rc/bricks_1.29.1-rc_linux_arm64.tar.gz"
        sha256 "42e8552e102c3fdbb065d39d350239e29af750e2b80a03d8178b71929fcc5329"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
