# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1531 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.53.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.53.1/bricks_1.53.1_darwin_all.tar.gz"
    sha256 "59b4a3afaa492a48bab5a4f346af5ba7fd075dd1d1e320b47c0e928e72cedb2a"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.53.1/bricks_1.53.1_linux_amd64.tar.gz"
      sha256 "359da4044a26cb5966f1ca210e14a1d09f6271a40e9fa6611cd8256f651e61e2"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.53.1/bricks_1.53.1_linux_arm64.tar.gz"
      sha256 "b18c459e380971ba8e3312e7685949b0c13eba702c8942aeaaab7438db9c7743"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
