# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1191 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.19.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.19.1/bricks_1.19.1_darwin_all.tar.gz"
    sha256 "1dab475ca6940e99d9712343971113861f373de1d3ac4152653c64b4aa3de2ac"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.19.1/bricks_1.19.1_linux_amd64.tar.gz"
        sha256 "177efe7aaa0964e46f33a0716f564a1c73f0a4fe8fd194cba77dccafa861b5d0"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.19.1/bricks_1.19.1_linux_arm64.tar.gz"
        sha256 "2c556ca0e3a24ad1d7e745b5cdaf2b622ee2f18c6b408554279159d57861e81d"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
