# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1870 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.87.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.87.0/bricks_1.87.0_darwin_all.tar.gz"
    sha256 "e16083871210e152e00f0974973d470d0badc1b85ddc0e7d8d9b3282d6a6ffb6"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.87.0/bricks_1.87.0_linux_amd64.tar.gz"
      sha256 "1f7fd72c90bcc80dfa3f9f23f716c36db2be818abce7bce783345a18689a43a6"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.87.0/bricks_1.87.0_linux_arm64.tar.gz"
      sha256 "3e682cded35d6e1601a20e20c17325b82d0e973404dd70f9f326743fd487f9ed"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
