# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1880Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.88.0-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.88.0-rc.1/bricks_1.88.0-rc.1_darwin_all.tar.gz"
    sha256 "934ca082d2fabd4f7090232ba838a2bc52f454809684efbc7a65c42299f75e86"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.88.0-rc.1/bricks_1.88.0-rc.1_linux_amd64.tar.gz"
      sha256 "ef49db5a7ea44bc0e223a909c09a572b12cb717e84bbb8039ef5d1e16b1362b6"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.88.0-rc.1/bricks_1.88.0-rc.1_linux_arm64.tar.gz"
      sha256 "0ac8b7d6a80def4b97da49c0fc285892bf67127058343a549531dae4d32e2835"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
