# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1780Rc1Publisher < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.78.0-rc.1-publisher"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.78.0-rc.1-publisher/bricks_1.78.0-rc.1-publisher_darwin_all.tar.gz"
    sha256 "6f6fc90db48a98294fc1c1796c44feb3d4159a1cc6ff73a07bb468814321b77d"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.78.0-rc.1-publisher/bricks_1.78.0-rc.1-publisher_linux_amd64.tar.gz"
      sha256 "67dcde6ba39940830a08657fec530c534d0e23c0b3cf62fc29208e9ecc081728"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.78.0-rc.1-publisher/bricks_1.78.0-rc.1-publisher_linux_arm64.tar.gz"
      sha256 "3984d725d104d0d444ee4784f356c17f9544fc542d9a3c209c62b603f559af5f"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
