# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1711Embed < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.71.1-embed"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.71.1-embed/bricks_1.71.1-embed_darwin_all.tar.gz"
    sha256 "9c8644956a2da99e7f7c0e3ae593c3aaeffcb6510fa6f7013ff9721cf2c6894d"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.71.1-embed/bricks_1.71.1-embed_linux_amd64.tar.gz"
      sha256 "1a909d65a58dd82619fdf10abbe5f6de50476f7043b9ed952d5dff18b165df47"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.71.1-embed/bricks_1.71.1-embed_linux_arm64.tar.gz"
      sha256 "e39e629568bf35421c120534d43fc227d64beecf832935467fa6acfef8c0c0d8"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
