# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1730ArtifactlessPrjTest < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.73.0-artifactless-prj-test"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.73.0-artifactless-prj-test/bricks_1.73.0-artifactless-prj-test_darwin_all.tar.gz"
    sha256 "ab1a2a5f70c44dc616edb223bbbc9d278b83c460947edb29bb61437cb694168b"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.73.0-artifactless-prj-test/bricks_1.73.0-artifactless-prj-test_linux_amd64.tar.gz"
      sha256 "ad08458f967544ceebfcfbcf0e63874a56a955d62c31026447e8e27c9162cdb7"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.73.0-artifactless-prj-test/bricks_1.73.0-artifactless-prj-test_linux_arm64.tar.gz"
      sha256 "2eb6d721f68f559996a7253127dd8bb2ce44a7e53b7c92eca285899418d484dc"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
