# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1782Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.78.2-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.78.2-rc/bricks_1.78.2-rc_darwin_all.tar.gz"
    sha256 "a82e6cca74b4e00a05ca9db452c34d179f6da76602511be3bc3a3afc97534504"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.78.2-rc/bricks_1.78.2-rc_linux_amd64.tar.gz"
      sha256 "1d173b097bbc0be1f4e38b4cf1c2886527ce60cfe1259849c7dbf658543c9007"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.78.2-rc/bricks_1.78.2-rc_linux_arm64.tar.gz"
      sha256 "166930b203783cf84b8e98c9cb9f2d1adb51aeffe943a7f7d4e365427e3abca6"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
