# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1114 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.11.4"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.11.4/bricks_1.11.4_darwin_all.tar.gz"
    sha256 "d84d80a20af68d91581b1a117848e02db63e2f3da5d1a14993042b84892e4d90"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.11.4/bricks_1.11.4_linux_amd64.tar.gz"
        sha256 "55f14da65bd9b16840b0b4de4f55c1bca4d60ac0f40832db44e4ecdfc3bf465c"

        def install
          bin.install "bricks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.11.4/bricks_1.11.4_linux_arm64.tar.gz"
        sha256 "964800debe3640ac518bb317fcd0630bfc6557b3c5fd13b495589a2c75845501"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
