# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1690Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.69.0-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.69.0-rc.1/bricks_1.69.0-rc.1_darwin_all.tar.gz"
    sha256 "9520b321459910c327997e36649dc9b93a12c9ebf878246e6fa1bb2c50b69d9b"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.69.0-rc.1/bricks_1.69.0-rc.1_linux_amd64.tar.gz"
      sha256 "c17b257faac0ce252db82e56688dccde094af68be873d9039d18e2cbe1b445c6"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.69.0-rc.1/bricks_1.69.0-rc.1_linux_arm64.tar.gz"
      sha256 "9d9136912c6bbb34e26a956667c70d5aaffacca96000164428a744da8854bc80"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
