# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1360 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.36.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.36.0/bricks_1.36.0_darwin_all.tar.gz"
    sha256 "5129b48e1bfbac87851da91806e9d004534d6cb1cae64e411108cc6b04b8c1a4"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.36.0/bricks_1.36.0_linux_amd64.tar.gz"
        sha256 "1cbb30434d75023c465deb72fd398e87c9047c2d721f699d3e04930ecf10eca3"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.36.0/bricks_1.36.0_linux_arm64.tar.gz"
        sha256 "6329051f2c37e8b8ca7181f130d40e2b28082b1618ebc57b984195c9fb882581"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
