# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT181 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.8.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.8.1/bricks_1.8.1_darwin_all.tar.gz"
    sha256 "2bb997674398fa2da1747da63e0a128213ba696fc876f5043ea9b839e98325aa"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.8.1/bricks_1.8.1_linux_amd64.tar.gz"
        sha256 "e72c2baa43158813f41bcb9a396259cb9df667c1b29b5bb2b300a79dc47f781d"

        def install
          bin.install "bricks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.8.1/bricks_1.8.1_linux_arm64.tar.gz"
        sha256 "24eab23c47a4661a7bdbdc36ca7e274219df03a8e789ed9af2f465e59a533235"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
