# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1331 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.33.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.33.1/bricks_1.33.1_darwin_all.tar.gz"
    sha256 "fa390364c0d30c8a436b1eb87830ee4dd21abbc7058f817606115f26fcd0cd2d"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.33.1/bricks_1.33.1_linux_amd64.tar.gz"
        sha256 "cf9d1a5b364544201637157a171c6b68e16590551728b7107679e238e2298442"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.33.1/bricks_1.33.1_linux_arm64.tar.gz"
        sha256 "67246c961d7bb747d4ea3136fbc19838434ca476642dcb0e1639389d31713a88"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
