# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1260Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.26.0-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.26.0-rc/bricks_1.26.0-rc_darwin_all.tar.gz"
    sha256 "9dead3b6cee8888b92ad648a5693c005dbe5245d83f1604e43e80f513615be09"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.26.0-rc/bricks_1.26.0-rc_linux_amd64.tar.gz"
        sha256 "16b35c0cf7536fe5aa8fb31822896cad42e62aadcebf883af939d388f42d4fda"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.26.0-rc/bricks_1.26.0-rc_linux_arm64.tar.gz"
        sha256 "db12f4b929ce5cfa52ce9bab0f4c9a1f4fa6c8f5d29fa50dcbdcd4cc508945f4"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
