# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1110 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.11.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.11.0/bricks_1.11.0_darwin_all.tar.gz"
    sha256 "90085bcb8f9cf3472116c83e53eac510d253c7d560e233095b6439bb4794ce71"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.11.0/bricks_1.11.0_linux_amd64.tar.gz"
        sha256 "45ff81ea6ddb0161fb0b0a3d4342b79b3c9e136355e1ebdff85bca1e54441a94"

        def install
          bin.install "bricks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.11.0/bricks_1.11.0_linux_arm64.tar.gz"
        sha256 "d684fe38847261c3defb67c83adf050c5008cd403c447bba784256737ae3bad4"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
