# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1671Rc3RetryTest500 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.67.1-rc-3-retry-test-500"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.1-rc-3-retry-test-500/bricks_1.67.1-rc-3-retry-test-500_darwin_all.tar.gz"
    sha256 "baab6082aea5e2bb76c976e6c06c8be7ca9e69ce0227600a0dddc1cec128f7be"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.1-rc-3-retry-test-500/bricks_1.67.1-rc-3-retry-test-500_linux_amd64.tar.gz"
      sha256 "a9ee3d3fb930530322bb018eeaee6bccdc6cdf2c454639b93b1d0439611e10f9"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.1-rc-3-retry-test-500/bricks_1.67.1-rc-3-retry-test-500_linux_arm64.tar.gz"
      sha256 "fc4ebddb45b62b48ad7ba05a7998fc48440cbc66506ef95327e21e68d5fcbe27"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
