# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1420 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.42.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.42.0/bricks_1.42.0_darwin_all.tar.gz"
    sha256 "496d311c5fe43a3fa3d40d596a4b7f33e8c18f27c5459a1351504209f4b8a5a1"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.42.0/bricks_1.42.0_linux_amd64.tar.gz"
        sha256 "37b708da6b7d6f4892f018dc2645c01d9e5cc424a951c2de4d1efd63ae8babbf"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.42.0/bricks_1.42.0_linux_arm64.tar.gz"
        sha256 "f830c154888f21e48b41d5482e16136a35d507e87b14ca348e0923d21db8709d"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
