# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1921Rc2FixImage < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.92.1-rc-2-fix-image"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.92.1-rc-2-fix-image/bricks_1.92.1-rc-2-fix-image_darwin_all.tar.gz"
    sha256 "57d8dfc7554154c680136735d0d2abb712e3136e9e4e9cdd2456d774829d166c"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.92.1-rc-2-fix-image/bricks_1.92.1-rc-2-fix-image_linux_amd64.tar.gz"
      sha256 "c1bce630265b3e95be63a6445567bd2c485716eb771ee8985fe2ec697801bdc7"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.92.1-rc-2-fix-image/bricks_1.92.1-rc-2-fix-image_linux_arm64.tar.gz"
      sha256 "3103465c7e6e8a259bbda0e3128c50366fa83f25a31d45360c71718f0774d876"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
