# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1125 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.12.5"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.12.5/bricks_1.12.5_darwin_all.tar.gz"
    sha256 "612a447ee68434cbd9acd5a9ed2a0d15d2f8f9806edc5749b4251f18f8d6da6c"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.12.5/bricks_1.12.5_linux_amd64.tar.gz"
        sha256 "b4e82f51a7b59529cd402b666e0467a89e67a7f738807d3190425be2315bdc28"

        def install
          bin.install "bricks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.12.5/bricks_1.12.5_linux_arm64.tar.gz"
        sha256 "65df13276f2d625f67ff6ecf2cf648a48fdce82abc33c6d2e4f0ce4e115c3685"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
