# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1530Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.53.0-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.53.0-rc/bricks_1.53.0-rc_darwin_all.tar.gz"
    sha256 "885ba90cb7c9b93e7968d37c9e870c5334590057db9e7e1d5165dd8362f55ffa"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.53.0-rc/bricks_1.53.0-rc_linux_amd64.tar.gz"
      sha256 "7da5478bfa3bc4e8420eae74754c356f960d3b96f14c10cb81aa61a4ac081ccc"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.53.0-rc/bricks_1.53.0-rc_linux_arm64.tar.gz"
      sha256 "8a554d0b1e316a12c50ad262fa1391d79ce47dda4150df5701fa27a1e41efbd9"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
