# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1680Rc2BicepIncremental < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.68.0-rc.2-bicep-incremental"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.68.0-rc.2-bicep-incremental/bricks_1.68.0-rc.2-bicep-incremental_darwin_all.tar.gz"
    sha256 "c018bfc7d6057923bd9683760b69d04fe2a0fc7fd97160672ce47f64c1a2cb17"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.68.0-rc.2-bicep-incremental/bricks_1.68.0-rc.2-bicep-incremental_linux_amd64.tar.gz"
      sha256 "da513c30dd481da5d55b83868b5c2771deb643ced067ddec1d0201551b4917c1"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.68.0-rc.2-bicep-incremental/bricks_1.68.0-rc.2-bicep-incremental_linux_arm64.tar.gz"
      sha256 "6b967286637e95c7cd7315eeb5418980f22928c7ec3e548987d336de66daf9dc"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
