# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1320Rc2 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.32.0-rc.2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.32.0-rc.2/bricks_1.32.0-rc.2_darwin_all.tar.gz"
    sha256 "4bf25ff88fd3119e2e48cea80fc93fccd99891358413a3d4f78e96cae8bdae8c"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.32.0-rc.2/bricks_1.32.0-rc.2_linux_amd64.tar.gz"
        sha256 "383fb3a2a102f3b0cdf5c779b77c58408b3e9c09b7f22d08cd8e28cca494ec2b"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.32.0-rc.2/bricks_1.32.0-rc.2_linux_arm64.tar.gz"
        sha256 "ebd22b9362ba5184927879e87395aed0fa6697afe8018509f09b64b862073176"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
