# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1201 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.20.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.20.1/bricks_1.20.1_darwin_all.tar.gz"
    sha256 "98ce929c8c6089837e68ff04f3dff19ea4766354f224896447a3da3a3aeb6c1f"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.20.1/bricks_1.20.1_linux_amd64.tar.gz"
        sha256 "63ce220bdd54a6f5b64c1320a8e2a207fc40d10a606fd2eb134d0381da861f8f"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.20.1/bricks_1.20.1_linux_arm64.tar.gz"
        sha256 "75db9b8c84f2428fe1666e98e4f62e4fc8e1785f11dfc45f7b7686de78ebac5d"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
