# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1311 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.31.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.31.1/bricks_1.31.1_darwin_all.tar.gz"
    sha256 "e826842caa8e8bc1de16b486747dfe020b09c0d17427684fdca5ecc946b9e850"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.31.1/bricks_1.31.1_linux_amd64.tar.gz"
        sha256 "15e586869ec02283a2b66849edd8b0128e9b906b5ae59d4b25339c338e963e71"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.31.1/bricks_1.31.1_linux_arm64.tar.gz"
        sha256 "9aee6098d094b31f042f29cbd7bed7b52069e425d496c942f17f1a7e9947c476"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
