# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1810Rc0AgentStateUpload < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.81.0-rc.0-agent-state-upload"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.81.0-rc.0-agent-state-upload/bricks_1.81.0-rc.0-agent-state-upload_darwin_all.tar.gz"
    sha256 "05c4bf15728f0deb046cfaf2e0f5c7a84c9a8e1b4735c6aa0199d865bbd030b6"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.81.0-rc.0-agent-state-upload/bricks_1.81.0-rc.0-agent-state-upload_linux_amd64.tar.gz"
      sha256 "0091dd32927032efa4a0f4a4d378ce36282fbb09c9e11fa5163f3afb684c6a2c"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.81.0-rc.0-agent-state-upload/bricks_1.81.0-rc.0-agent-state-upload_linux_arm64.tar.gz"
      sha256 "bf0320dee90ff0596565303e80e258132d38d04ec857bb0f1ac509e6006700cf"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
