# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1573 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.57.3"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.57.3/bricks_1.57.3_darwin_all.tar.gz"
    sha256 "2af555aa0c652e5be5039638eb5cee1107c7b7164a20e05726f3b21a50a129f0"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.57.3/bricks_1.57.3_linux_amd64.tar.gz"
      sha256 "6171ff667996578dcc0b38ca412d450213c2cbe26fa732513b109e470d05adbd"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.57.3/bricks_1.57.3_linux_arm64.tar.gz"
      sha256 "562ba6b6a13e6201028913ac49c2a16c0bbb55919461b059abcd90ee53d65ef6"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
