# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1387Dev < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.38.7-dev"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.38.7-dev/bricks_1.38.7-dev_darwin_all.tar.gz"
    sha256 "19918881cc841a9240dabbb63e6d77d2ba1b93600ab518d9b0c499cc5e42d47b"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.38.7-dev/bricks_1.38.7-dev_linux_amd64.tar.gz"
        sha256 "9cc99e5e2eb574f227cdbeffde966deb61bc180c47111e40722dab8ccc763227"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.38.7-dev/bricks_1.38.7-dev_linux_arm64.tar.gz"
        sha256 "e666379f3ba5a8e2c72f65ee7bd94fa0f529b59b4ecf1ce431e8011f5d1eb47f"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
