# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1430 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.43.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.43.0/bricks_1.43.0_darwin_all.tar.gz"
    sha256 "5ad2a0375f36046493e26c03c42489593d71fae23c28c27812a79247d61d558d"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.43.0/bricks_1.43.0_linux_amd64.tar.gz"
        sha256 "bb149c1c836c05fbe4dd9ba2731af4a8b88576a901ca689a10c4e229164c3f4f"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.43.0/bricks_1.43.0_linux_arm64.tar.gz"
        sha256 "6ad154858116ff579fd092422dd32da38d475052071e881ab9ca9499eb0ab5be"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
