# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1530 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.53.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.53.0/bricks_1.53.0_darwin_all.tar.gz"
    sha256 "d499e33b981b47c9fdc26db2f550901ce8e4a1206de31c380286aeadd2611137"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.53.0/bricks_1.53.0_linux_amd64.tar.gz"
      sha256 "9ba9d8d627881d065cb1013f5c6311aa5ce220583534392a77ed4f82e3f0bf4f"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.53.0/bricks_1.53.0_linux_arm64.tar.gz"
      sha256 "fc9fb387d23a3478ff795bd68a718972b71e8dedaa180d4143e829d63690bddc"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
