# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1430Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.43.0-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.43.0-rc/bricks_1.43.0-rc_darwin_all.tar.gz"
    sha256 "21ccebf3ee01cd75172c3517082600c8373652301432f29471310f75b672e773"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.43.0-rc/bricks_1.43.0-rc_linux_amd64.tar.gz"
        sha256 "e7a72b21f80160bbc6a018ca31fd41eb1d92032c5cfbc3460bc6a151c5100954"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.43.0-rc/bricks_1.43.0-rc_linux_arm64.tar.gz"
        sha256 "9c34639f10e7a39823a00788dfc564a493d57fbb0d6b345803edeea6ae71d2f2"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
