# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1360Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.36.0-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.36.0-rc/bricks_1.36.0-rc_darwin_all.tar.gz"
    sha256 "9bc5debcef9d4ebda6496d2c88f36f3c7f536bcab291179b3d19442ff53b4721"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.36.0-rc/bricks_1.36.0-rc_linux_amd64.tar.gz"
        sha256 "b613460525cb86c92cd1c6fa9d6d553d62d8683ec6440d4d4e889b197f6b8727"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.36.0-rc/bricks_1.36.0-rc_linux_arm64.tar.gz"
        sha256 "d2f3e9332d3b44fa5323782ce57679b5a1bc0624c187e31e594fb0b16280c359"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
