# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1102 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.10.2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.10.2/bricks_1.10.2_darwin_all.tar.gz"
    sha256 "6b016d21045e8f1280a7bf6e873d4c1f983c367918f7544a93b8a92bdd79bfb4"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.10.2/bricks_1.10.2_linux_amd64.tar.gz"
        sha256 "89beff5781c4f24a55214f1d78fdc1fa75e380b6b0ee63609ebd955e5e403306"

        def install
          bin.install "bricks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.10.2/bricks_1.10.2_linux_arm64.tar.gz"
        sha256 "568e402b71878bed4044a119e1fe9f20d20c9322f651bb1ed8355f7d82134e85"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
