# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1200Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.20.0-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.20.0-rc/bricks_1.20.0-rc_darwin_all.tar.gz"
    sha256 "be7f0dafa1c0a2b158f283fe8807d56af7b5e9abea3b3c6bfc77613c74b16bf6"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.20.0-rc/bricks_1.20.0-rc_linux_amd64.tar.gz"
        sha256 "2595cfe348cc9cc588cabfddfc09887d88a91f71518f37d8a4cea2b724423e59"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.20.0-rc/bricks_1.20.0-rc_linux_arm64.tar.gz"
        sha256 "20b755142fc36dc6943d293e2fc593542692e893491c0f6714716896a1c98160"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
