# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1261 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.26.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.26.1/bricks_1.26.1_darwin_all.tar.gz"
    sha256 "f9b4da2e76fa6a6b6327a32d22cab992cec0c11842fc99add883b6df156ddcd0"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.26.1/bricks_1.26.1_linux_amd64.tar.gz"
        sha256 "b5ae0267b2f82d30f43b3e970fafe0a0b82f6e24684baae3503320bea2603665"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.26.1/bricks_1.26.1_linux_arm64.tar.gz"
        sha256 "e3ad2cefdfa3ebc27afcae135e31a6bf26bc6e5cdea0a41c237d5310291e57e7"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
