# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1540 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.54.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.54.0/bricks_1.54.0_darwin_all.tar.gz"
    sha256 "0af65298cbc00dfc8d96eb19dde240e2ddc454e4d23ec94c6b8f6f8786cc3a71"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.54.0/bricks_1.54.0_linux_amd64.tar.gz"
      sha256 "de75396237bed370454d8d6ef78ccfae60da16e82f30e52b6ddb155186e4ba0b"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.54.0/bricks_1.54.0_linux_arm64.tar.gz"
      sha256 "4358e3d271e50691d91251e330a135601d3a9d9f73de2b0c0acb0188d9d70b10"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
