# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1730ArtifactlessPrjTestLogs1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.73.0-artifactless-prj-test-logs-1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.73.0-artifactless-prj-test-logs-1/bricks_1.73.0-artifactless-prj-test-logs-1_darwin_all.tar.gz"
    sha256 "4b3bb6360e43b985affa9c1b3c9285705903cb7fa2b05e1100b94e0c517f5ebd"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.73.0-artifactless-prj-test-logs-1/bricks_1.73.0-artifactless-prj-test-logs-1_linux_amd64.tar.gz"
      sha256 "18a7ca7e2f56bdcc2b9be779a82d6e4ab77efda238f2f1b4985ee28e4dae2dc4"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.73.0-artifactless-prj-test-logs-1/bricks_1.73.0-artifactless-prj-test-logs-1_linux_arm64.tar.gz"
      sha256 "e5adb6e7aea5a9c7a7ac754377c1078121d99cfc5e8a91c07ec3d5d3eaf07fec"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
