# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1970 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.97.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.97.0/bricks_1.97.0_darwin_all.tar.gz"
    sha256 "31a33c16d1780e8d69b101c6c79e1a672c888039b84d03d042dce1d78da4d351"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.97.0/bricks_1.97.0_linux_amd64.tar.gz"
      sha256 "c95905c5340f10888c804a54e2696fb3231c691b274e9460779a67f01d767336"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.97.0/bricks_1.97.0_linux_arm64.tar.gz"
      sha256 "c4fc622e7157881d820d5400105a4fd457ed120fa038a9243269572f3df8a6d2"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
