# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1671Rc4RetryTest404 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.67.1-rc-4-retry-test-404"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.1-rc-4-retry-test-404/bricks_1.67.1-rc-4-retry-test-404_darwin_all.tar.gz"
    sha256 "afb27c0f3ce853683fb23563708eaff3addd9afc85cd2c9a2a69a3eeecfbcd06"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.1-rc-4-retry-test-404/bricks_1.67.1-rc-4-retry-test-404_linux_amd64.tar.gz"
      sha256 "b86805ba727ce4c79a8117699ff5ea2c2b67bd0556ab27abc0bcc9ba133b94c5"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.1-rc-4-retry-test-404/bricks_1.67.1-rc-4-retry-test-404_linux_arm64.tar.gz"
      sha256 "2e0f8edc533e44c4e6e885528094b7481747b78b2cb2fa219c448433a9cf636f"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
