# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1211Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.21.1-rc"
  license ":cannot_represent"
  depends_on :linux

  if Hardware::CPU.intel?
    if Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.21.1-rc/bricks_1.21.1-rc_linux_amd64.tar.gz"
      sha256 "43415646d38300de86f34e3f9bcb330014b42616edc71275dd4479078c98cb2a"

      def install
        bin.install "bricks"
      end
    end
  end
  if Hardware::CPU.arm?
    if Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.21.1-rc/bricks_1.21.1-rc_linux_arm64.tar.gz"
      sha256 "4a422eb3673e71725c0c814836665d444e31b79e8ca3e85ebdaa328d551328f1"

      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
