# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1880Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.88.0-rc1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.88.0-rc1/bricks_1.88.0-rc1_darwin_all.tar.gz"
    sha256 "0d4ad58404682205a3fde0c62b7188ce17e92ef5e43983edfb0cf7b83cc571ca"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.88.0-rc1/bricks_1.88.0-rc1_linux_amd64.tar.gz"
      sha256 "978c8500876b5d1ef7b735e02b5f0dc5fdbd3ca00dbb98b080bd7d4ecd89e809"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.88.0-rc1/bricks_1.88.0-rc1_linux_arm64.tar.gz"
      sha256 "9b0c227ba48c89f5da63888e7880f6edc20c57fae473a1d61a229f4f42747175"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
