# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1730Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.73.0-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.73.0-rc.1/bricks_1.73.0-rc.1_darwin_all.tar.gz"
    sha256 "631aa52bfe7d729c6a8b7838abfa6ea024df87483cacbabd08319128a9fa25b1"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.73.0-rc.1/bricks_1.73.0-rc.1_linux_amd64.tar.gz"
      sha256 "a85f1a307c9fe994d642cc2ec64084177a1d7dbf5f1eb642fd550027b7f92d6f"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.73.0-rc.1/bricks_1.73.0-rc.1_linux_arm64.tar.gz"
      sha256 "1a7c110fde0b8779bc5a870fb59f3fcbe346d26cc92cf7c7cde5095f769bd1e7"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
