# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1921 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.92.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.92.1/bricks_1.92.1_darwin_all.tar.gz"
    sha256 "9452e42203f13991de29aa06729a6df73de05a76a62f3c7ff9427305ef0d6f86"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.92.1/bricks_1.92.1_linux_amd64.tar.gz"
      sha256 "5dace7eaf182b992e1828c262e82438f99d4561e4f53210df2d93590167bd7a7"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.92.1/bricks_1.92.1_linux_arm64.tar.gz"
      sha256 "61e05afda0d661fafa90920b03f04582dd1d7e0bba9564fc84abb9b1fbebe46a"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
