# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1450Rc < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.45.0-rc"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.45.0-rc/bricks_1.45.0-rc_darwin_all.tar.gz"
    sha256 "51e6104eebafcec83303d993e3fae53d290e7688fd90c3aca63d34ccf1941eb8"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.45.0-rc/bricks_1.45.0-rc_linux_amd64.tar.gz"
      sha256 "332554ab0dfe82187d063f8bf2048e26f9614cfa84f491e41fdce821e52574a4"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.45.0-rc/bricks_1.45.0-rc_linux_arm64.tar.gz"
      sha256 "d2f475e2f64d6f70d43922d09e4b56fc46aa1e5bb00dfaae65393829afca3d4a"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
