# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT170 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.7.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.7.0/bricks_1.7.0_darwin_all.tar.gz"
    sha256 "717ce6050990a3291665fbc4fe2cc9d73d28e2052a7d00f0ea163586acceaba5"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.7.0/bricks_1.7.0_linux_amd64.tar.gz"
        sha256 "097678d1217a516d601e071562fe92181e1524106829c4ee05dc87ea7785d055"

        def install
          bin.install "bricks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.7.0/bricks_1.7.0_linux_arm64.tar.gz"
        sha256 "7bbbdaef82e964c41a14bed978e0c6b33297411460f9077cf21287f102fb857c"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
