# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1183 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.18.3"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.18.3/bricks_1.18.3_darwin_all.tar.gz"
    sha256 "0c2169fdff5e2de1d60a727ed7df4e520fa3fd1df65fbdfd64ffdcfbdb70207f"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.18.3/bricks_1.18.3_linux_amd64.tar.gz"
        sha256 "4c6f0b106277af2dcd949551ed5e0eddc86def6de8e3f8838eec85ae1a0c8f3f"

        def install
          bin.install "bricks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.18.3/bricks_1.18.3_linux_arm64.tar.gz"
        sha256 "cae3faacef9f9df3aac3884f52b43ce8838f6d602525cfed0f50789420bda736"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
