# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1552 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.55.2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.55.2/bricks_1.55.2_darwin_all.tar.gz"
    sha256 "e4b548efe2713d040e5a60bdf2b0dfc3ffb5b60749d368b24e14ce755ba3e4a9"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.55.2/bricks_1.55.2_linux_amd64.tar.gz"
      sha256 "6ff26a88f07c3038f71a5acb0af14b7af87e06546c7d0ce8ea5fa1a9c6fbc002"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.55.2/bricks_1.55.2_linux_arm64.tar.gz"
      sha256 "1cb83ec7c821274c0178e04342b7583c1e0ff975ed99559a00118f493a1dfed8"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
