# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1620Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.62.0-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.62.0-rc.1/bricks_1.62.0-rc.1_darwin_all.tar.gz"
    sha256 "7df7c525049e5007440efb048a287af35d1af1a33a8a200fb8540b9d10699b2f"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.62.0-rc.1/bricks_1.62.0-rc.1_linux_amd64.tar.gz"
      sha256 "db6c23c9c412d4e4845ebb143aea9faf7922f112dd0499d1d0114e9bc0d62209"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.62.0-rc.1/bricks_1.62.0-rc.1_linux_arm64.tar.gz"
      sha256 "cab1685de360e2ba8a908148b2e3619147a6db65c8b414b8cbfc604883cd2eff"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
