# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1761Rc2 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.76.1-rc.2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.76.1-rc.2/bricks_1.76.1-rc.2_darwin_all.tar.gz"
    sha256 "32245823c8b491aa53adae8a8b478f57248a6d93dc9ea5423d51c5bbea13d460"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.76.1-rc.2/bricks_1.76.1-rc.2_linux_amd64.tar.gz"
      sha256 "a0c37609c714fb55a3f648756611e4902f6c665e5a6666c7839658209e6831f1"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.76.1-rc.2/bricks_1.76.1-rc.2_linux_arm64.tar.gz"
      sha256 "e817f5873e5de0bbb64043583e5ccb8b9cf064f1c0cc90bbfc3bc9526fd59165"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
