# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1671Rc5RetryTestTimeout < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.67.1-rc-5-retry-test-timeout"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.1-rc-5-retry-test-timeout/bricks_1.67.1-rc-5-retry-test-timeout_darwin_all.tar.gz"
    sha256 "6bc77397db47364f979b710bd3d7336b3720e1d009b348865d8e05cc757eb621"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.1-rc-5-retry-test-timeout/bricks_1.67.1-rc-5-retry-test-timeout_linux_amd64.tar.gz"
      sha256 "3cd6350ee3c1d712106c59b36cceb7548dd2390e29ad54c67dce9dc082e6039b"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.67.1-rc-5-retry-test-timeout/bricks_1.67.1-rc-5-retry-test-timeout_linux_arm64.tar.gz"
      sha256 "bc8757d687be7ebe053ab5ef16adc1595c522fa4a5fd623900e827c162a2070d"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
