# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1850Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.85.0-rc.1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.85.0-rc.1/bricks_1.85.0-rc.1_darwin_all.tar.gz"
    sha256 "8015f37caad8ec50a6f40939e8833956f558a742748c62edd2ca84c5c0648c13"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.85.0-rc.1/bricks_1.85.0-rc.1_linux_amd64.tar.gz"
      sha256 "61f2c0fccaca02600c5a6acf8c6a08b95ca7f56e3e016db241ed9417d1513285"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.85.0-rc.1/bricks_1.85.0-rc.1_linux_arm64.tar.gz"
      sha256 "453c49b0f2ef407fbc2ec73f566165b254c7456d255d6ba9f00996dba8e83dcf"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
