# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1830Rc2 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.83.0-rc.2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.83.0-rc.2/bricks_1.83.0-rc.2_darwin_all.tar.gz"
    sha256 "e536ba0348e56ec88ae48dbc67c443d6f9a63cccf613d7017332a2f3c688f936"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.83.0-rc.2/bricks_1.83.0-rc.2_linux_amd64.tar.gz"
      sha256 "08baaf15af3781123966b6186b93045c8ecb2f7dd22071362e1288f75993af48"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.83.0-rc.2/bricks_1.83.0-rc.2_linux_arm64.tar.gz"
      sha256 "82a02b611c654a6e386e645b303d5ee0d56610f7d5de795d4b35caa36bac3849"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
