# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1600Rc1 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.60.0-rc1"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.60.0-rc1/bricks_1.60.0-rc1_darwin_all.tar.gz"
    sha256 "07ed1925d03140bd1f9de27c9cace6c745d35d2f09a318d2add2f6e904ae42da"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.60.0-rc1/bricks_1.60.0-rc1_linux_amd64.tar.gz"
      sha256 "c14d2ca2c65bdd7c936c44c09d5ef304fd915b6a97a327d54f3453f67bdb7ea7"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.60.0-rc1/bricks_1.60.0-rc1_linux_arm64.tar.gz"
      sha256 "5522ba3d7bdd0d021dfc0cd67c8910041e9a57324401861b918f95e0d5d0b414"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
