# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1170 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.17.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.17.0/bricks_1.17.0_darwin_all.tar.gz"
    sha256 "951bd879d8c793298b892e999360766a682d383358a64f21ea29a364aa85e923"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.17.0/bricks_1.17.0_linux_amd64.tar.gz"
        sha256 "b99b3ece1414c835f2c5c06f8e1e220a5c5c06167a55de5384ea2a72ae4e426e"

        def install
          bin.install "bricks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.17.0/bricks_1.17.0_linux_arm64.tar.gz"
        sha256 "603418d96c704d7d2a4005ee91d13547b6440dc920b55ed6d888a117f4e61242"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
