# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT1850Rc2 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.85.0-rc.2"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.85.0-rc.2/bricks_1.85.0-rc.2_darwin_all.tar.gz"
    sha256 "d6e2d65b238a6bde988bb22858f3777c38d768b0a5b4a1a29ce2a63850aeaa57"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.85.0-rc.2/bricks_1.85.0-rc.2_linux_amd64.tar.gz"
      sha256 "3e9bb3ad03da5dca7bd1288ed01007833ccd7af7a8f9b6fd051940fdfd02f27a"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.85.0-rc.2/bricks_1.85.0-rc.2_linux_arm64.tar.gz"
      sha256 "086224c8d087008c797acf747ff741ce51b33fcd3d8832242394094de7a9182d"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
