# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT190Canary < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.9.0-canary"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.9.0-canary/bricks_1.9.0-canary_darwin_all.tar.gz"
    sha256 "82a0c75de85482d826a38475826052a1db4d5dfd9f3ae5ffdc500df9be3e09da"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.9.0-canary/bricks_1.9.0-canary_linux_amd64.tar.gz"
        sha256 "ba3c1d250c580bf1c2f212b1b2d966fa225f3805556d0cb8bff4263408bf99d0"

        def install
          bin.install "bricks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.9.0-canary/bricks_1.9.0-canary_linux_arm64.tar.gz"
        sha256 "857d49b446fc496d325bae1f9beea8f059252b89f6f466d740d441021579da36"

        def install
          bin.install "bricks"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
