# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BricksAT11000 < Formula
  desc "Bricks CLI - Infrastructure Control Plane and Orchestration"
  homepage "https://bluebricks.co"
  version "1.100.0"
  license ":cannot_represent"

  on_macos do
    url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.100.0/bricks_1.100.0_darwin_all.tar.gz"
    sha256 "ec83b3ce66e0db2cecab35646df255542ce5b5f276c595119e820bbc8fcebfaa"

    def install
      bin.install "bricks"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.100.0/bricks_1.100.0_linux_amd64.tar.gz"
      sha256 "239e2c8fa1c7b0c2387496ed8a08a98ad2b16670d671f84fdf0f350f0434a00c"
      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://brickscli.s3.eu-west-1.amazonaws.com/releases/1.100.0/bricks_1.100.0_linux_arm64.tar.gz"
      sha256 "546564bee1c888777c8dac4456ade454a6222346ed8ca466ff3867431d3b7ea4"
      def install
        bin.install "bricks"
      end
    end
  end

  def caveats
    <<~EOS
      Thank you for installing bricks! 🧱 See more documentation at https://docs.bluebricks.co.
      Run 'bricks --help' to get started.
    EOS
  end

  test do
    system "#{bin}/bricks --version"
  end
end
